import type { FaqItem } from "@/lib/assistant/faq-types";

const R = ["/", "/listings", "/dashboard", "/dashboard/listings/"] as const;

export const FAQ_TROUBLESHOOTING: FaqItem[] = [
  {
    id: "troubleshoot-calendar-not-opening",
    question: "Δεν ανοίγει το ημερολόγιο. Τι κάνω;",
    answer:
      "1. Κάνε hard refresh (Ctrl+Shift+R).\n2. Δοκίμασε άλλο browser.\n3. Έλεγξε αν μπλοκάρει extension.\n4. Αν συνεχίζει, στείλε αίτημα στην υποστήριξη από τον Βοηθό Midora.",
    category: "troubleshooting",
    audience: "all",
    relatedRoutes: [...R],
    priority: 92,
    quickSuggestion: false,
    suggestionContexts: ["public_search", "public_listing", "owner_availability"],
    keywords: ["ημερολογ", "calendar", "δεν ανοιγ"],
  },
  {
    id: "troubleshoot-changes-not-saving",
    question: "Δεν αποθηκεύονται οι αλλαγές μου. Τι κάνω;",
    answer:
      "1. Έλεγξε σύνδεση internet.\n2. Πάτησε ρητά Αποθήκευση.\n3. Μην κλείσεις τη σελίδα πριν ολοκληρωθεί.\n4. Hard refresh και ξαναδοκίμασε.\n5. Αν συνεχίζει, επικοινώνησε με υποστήριξη.",
    category: "troubleshooting",
    audience: "owner",
    relatedRoutes: ["/dashboard/listings/"],
    priority: 95,
    quickSuggestion: false,
    suggestionContexts: ["owner_listing_workspace"],
    keywords: ["αποθηκευ", "save", "δεν σωζ"],
  },
  {
    id: "troubleshoot-photos-not-showing",
    question: "Δεν εμφανίζονται οι φωτογραφίες μου.",
    answer:
      "1. Περίμενε να ολοκληρωθεί το upload.\n2. Έλεγξε μορφή (JPG, PNG, WebP).\n3. Refresh τη σελίδα.\n4. Δες αν η αγγελία είναι δημοσιευμένη.\n5. Αν λείπουν ακόμα, στείλε αίτημα υποστήριξης.",
    category: "troubleshooting",
    audience: "owner",
    relatedRoutes: ["/dashboard/listings/"],
    priority: 90,
    quickSuggestion: false,
    suggestionContexts: ["owner_photos"],
    keywords: ["φωτογραφ", "photos", "δεν εμφανιζ"],
    actionLinks: [{ label: "Φωτογραφίες", href: "/dashboard/listings/{id}/photos" }],
  },
  {
    id: "troubleshoot-cannot-upload-photos",
    question: "Δεν μπορώ να ανεβάσω φωτογραφίες.",
    answer:
      "1. Έλεγξε μέγεθος/μορφή αρχείου.\n2. Δοκίμασε λιγότερες φωτογραφίες κάθε φορά.\n3. Έλεγξε σύνδεση.\n4. Hard refresh.\n5. Αν αποτυγχάνει συνεχώς, επικοινώνησε με υποστήριξη.",
    category: "troubleshooting",
    audience: "owner",
    relatedRoutes: ["/dashboard/listings/"],
    priority: 88,
    quickSuggestion: false,
    suggestionContexts: ["owner_photos"],
    keywords: ["upload", "ανεβασ", "φωτογραφ"],
    actionLinks: [{ label: "Φωτογραφίες", href: "/dashboard/listings/{id}/photos" }],
  },
  {
    id: "troubleshoot-cannot-find-listing",
    question: "Δεν βρίσκω την αγγελία μου.",
    answer:
      "1. Πήγαινε στο /dashboard/listings.\n2. Έλεγξε φίλτρα (ενεργές/πρόχειρες).\n3. Αν είναι draft, άνοιξέ την από τη λίστα.\n4. Αν δημιούργησες νέα, ψάξε με τίτλο στην λίστα.",
    category: "troubleshooting",
    audience: "owner",
    relatedRoutes: ["/dashboard/listings"],
    priority: 85,
    quickSuggestion: false,
    suggestionContexts: ["owner_dashboard"],
    keywords: ["βρισκ", "find", "αγγελια"],
    actionLinks: [{ label: "Αγγελίες μου", href: "/dashboard/listings" }],
  },
  {
    id: "troubleshoot-back-to-search",
    question: "Δεν μπορώ να γυρίσω πίσω στην αναζήτηση.",
    answer:
      "Χρησιμοποίησε «Πίσω στην αναζήτηση» στην αγγελία ή το browser back. Αν χάθηκαν φίλτρα, ξανακάνε αναζήτηση από /listings — τα κριτήρια μπορεί να μην διατηρούνται πάντα.",
    category: "troubleshooting",
    audience: "visitor",
    relatedRoutes: ["/listings/", "/listings"],
    priority: 80,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["πισω", "back", "αναζητηση"],
    actionLinks: [{ label: "Αναζήτηση", href: "/listings" }],
  },
  {
    id: "troubleshoot-map-not-working",
    question: "Δεν λειτουργεί ο χάρτης.",
    answer:
      "1. Hard refresh (Ctrl+Shift+R).\n2. Έλεγξε σύνδεση.\n3. Δοκίμασε χωρίς ad-blocker στον χάρτη.\n4. Αν συνεχίζει, χρησιμοποίησε λίστα αποτελεσμάτων χωρίς χάρτη.",
    category: "troubleshooting",
    audience: "visitor",
    relatedRoutes: ["/listings"],
    priority: 78,
    quickSuggestion: false,
    suggestionContexts: ["public_search"],
    keywords: ["χαρτης", "map", "δεν δουλευ"],
  },
  {
    id: "troubleshoot-map-zoom",
    question: "Δεν μπορώ να κάνω zoom στον χάρτη.",
    answer:
      "Χρησιμοποίησε scroll/pinch zoom ή τα κουμπιά +/- στον χάρτη. Αν δεν ανταποκρίνεται, κάνε refresh. Σε mobile, δοκίμασε δύο δάχτυλα pinch.",
    category: "troubleshooting",
    audience: "visitor",
    relatedRoutes: ["/listings"],
    priority: 72,
    quickSuggestion: false,
    suggestionContexts: ["public_search"],
    keywords: ["zoom", "χαρτης", "map"],
  },
  {
    id: "troubleshoot-listing-not-public",
    question: "Δεν εμφανίζεται η αγγελία μου δημόσια.",
    answer:
      "1. Καρτέλα Δημοσίευση — είναι ενεργή;\n2. Πληρότητα — λείπουν φωτογραφίες/τιμές;\n3. Status «σε έλεγχο» ή παύση;\n4. Αποθήκευσε και ξαναδημοσίευσε.\n5. Αν OK αλλά δεν φαίνεται, επικοινώνησε υποστήριξη.",
    category: "troubleshooting",
    audience: "owner",
    relatedRoutes: ["/dashboard/listings/"],
    priority: 93,
    quickSuggestion: false,
    suggestionContexts: ["owner_dashboard", "owner_listing_workspace"],
    keywords: ["δημοσια", "public", "δεν εμφανιζ"],
    actionLinks: [{ label: "Δημοσίευση", href: "/dashboard/listings/{id}/publish" }],
  },
  {
    id: "troubleshoot-no-messages",
    question: "Δεν λαμβάνω μηνύματα.",
    answer:
      "1. Έλεγξε καρτέλα Αιτήματα της αγγελίας.\n2. Έλεγξε notifications/email.\n3. Βεβαιώσου ότι η αγγελία είναι δημοσιευμένη.\n4. Αν είσαι co-host, έλεγξε δικαιώματα μηνυμάτων.\n5. Αν συνεχίζει, στείλε αίτημα υποστήριξης.",
    category: "troubleshooting",
    audience: "owner",
    relatedRoutes: ["/dashboard/listings/"],
    priority: 86,
    quickSuggestion: false,
    suggestionContexts: ["owner_messages"],
    keywords: ["μηνυμα", "messages", "δεν λαμβαν"],
    actionLinks: [{ label: "Αιτήματα", href: "/dashboard/listings/{id}/inquiries" }],
  },
  {
    id: "troubleshoot-cannot-add-cohost",
    question: "Δεν μπορώ να προσθέσω συνοικοδεσπότη.",
    answer:
      "1. Μόνο ο ιδιοκτήτης προσκαλεί co-host.\n2. Max 5 συνοικοδεσπότες ανά αγγελία.\n3. Έλεγξε σωστό email.\n4. Αν είσαι co-host, δεν μπορείς να προσκαλέσεις άλλους (default).\n5. Αν αποτυγχάνει, επικοινώνησε υποστήριξη.",
    category: "troubleshooting",
    audience: "owner",
    relatedRoutes: ["/dashboard/listings/"],
    priority: 75,
    quickSuggestion: false,
    suggestionContexts: ["owner_listing_workspace"],
    keywords: ["συνοικοδεσποτ", "cohost", "προσκληση"],
    actionLinks: [{ label: "Συνοικοδεσπότες", href: "/dashboard/listings/{id}/cohosts" }],
  },
  {
    id: "troubleshoot-cannot-add-external-link",
    question: "Δεν μπορώ να βάλω εξωτερικό link.",
    answer:
      "1. Χρησιμοποίησε έγκυρο HTTPS URL.\n2. Επίλεξε πλατφόρμα.\n3. Αποθήκευσε από Καταχώριση → Σύνδεσμοι.\n4. Το Midora δεν κάνει import — μόνο επικόλληση URL.\n5. Αν αποτυγχάνει validation, δοκίμασε άλλο link.",
    category: "troubleshooting",
    audience: "owner",
    relatedRoutes: ["/dashboard/listings/"],
    priority: 74,
    quickSuggestion: false,
    suggestionContexts: ["owner_listing_workspace"],
    keywords: ["εξωτερικ", "link", "url"],
    actionLinks: [{ label: "Σύνδεσμοι", href: "/dashboard/listings/{id}/edit#external-links" }],
  },
  {
    id: "troubleshoot-wrong-price",
    question: "Η τιμή δεν υπολογίζεται σωστά.",
    answer:
      "1. Έλεγξε τιμές ανά ημέρα στο ημερολόγιο (Σαββατοκύριακο, ειδικές περίοδοι).\n2. Έλεγξε ελάχιστη διαμονή.\n3. Αποθήκευσε και refresh δημόσια αγγελία.\n4. Η τιμή είναι ενδεικτική — τελική επιβεβαίωση από ιδιοκτήτη.",
    category: "troubleshooting",
    audience: "all",
    relatedRoutes: ["/listings/", "/dashboard/listings/"],
    priority: 82,
    quickSuggestion: false,
    suggestionContexts: ["public_listing", "owner_availability"],
    keywords: ["τιμη", "price", "λάθος", "υπολογ"],
  },
  {
    id: "troubleshoot-dates-lost",
    question: "Οι ημερομηνίες που διάλεξα χάθηκαν.",
    answer:
      "Οι ημερομηνίες μπορεί να μην διατηρούνται μετά navigation. Ξαναεπίλεξέ τες στην αγγελία ή αναζήτηση. Για αναζήτηση, βάλε ξανά dates στο search bar πριν στείλεις αίτημα.",
    category: "troubleshooting",
    audience: "visitor",
    relatedRoutes: ["/listings/", "/listings"],
    priority: 70,
    quickSuggestion: false,
    suggestionContexts: ["public_listing", "public_search"],
    keywords: ["ημερομην", "dates", "χαθηκαν"],
  },
  {
    id: "troubleshoot-wrong-rental-mode",
    question: "Με γυρίζει λάθος από βραχυχρόνια σε μηνιαία.",
    answer:
      "Έλεγξε το tab Βραχυχρόνια/Μηνιαία στη γραμμή αναζήτησης ή στην αγγελία. Το mode δεν αλλάζει αυτόματα — επίλεξε ρητά τον τύπο μίσθωσης πριν την αναζήτηση ή το αίτημα.",
    category: "troubleshooting",
    audience: "visitor",
    relatedRoutes: ["/listings", "/listings/"],
    priority: 68,
    quickSuggestion: false,
    suggestionContexts: ["public_search", "public_listing"],
    keywords: ["βραχυχρον", "μηνιαι", "mode", "switch"],
  },
];
