import type { FaqItem } from "@/lib/assistant/faq-types";

const R = ["/listings/", "/dashboard/"] as const;

export const FAQ_INQUIRIES: FaqItem[] = [
  {
    id: "inquiries-send-generic",
    question: "Πώς στέλνω αίτημα;",
    answer:
      "Βραχυχρόνια: επίλεξε ημερομηνίες, γράψε μήνυμα και πάτησε «Στείλε αίτημα διαθεσιμότητας».\nΜηνιαία: επίλεξε μήνα/διάρκεια, γράψε μήνυμα και πάτησε «Στείλε αίτημα μίσθωσης».\n\nΤο Midora δεν ολοκληρώνει κρατήσεις ή πληρωμές — η τελική συμφωνία επιβεβαιώνεται από τον ιδιοκτήτη.",
    category: "inquiries",
    audience: "visitor",
    relatedRoutes: [...R],
    relatedFeature: "inquiry",
    priority: 102,
    quickSuggestion: true,
    suggestionContexts: ["public_listing", "home"],
    keywords: ["αιτημα", "στελν", "inquiry", "επικοινων"],
  },
  {
    id: "inquiries-send-availability",
    question: "Πώς στέλνω αίτημα διαθεσιμότητας;",
    answer:
      "1. Άνοιξε βραχυχρόνια αγγελία.\n2. Επίλεξε ημερομηνίες και επισκέπτες (προαιρετικά).\n3. Γράψε μήνυμα στον ιδιοκτήτη.\n4. Πάτησε «Στείλε αίτημα διαθεσιμότητας».\n\nΤο Midora δεν ολοκληρώνει κρατήσεις — η τελική συμφωνία επιβεβαιώνεται από τον ιδιοκτήτη.",
    category: "inquiries",
    audience: "visitor",
    relatedRoutes: [...R],
    relatedFeature: "inquiry",
    priority: 100,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["αιτημα", "διαθεσιμοτητα", "inquiry", "στελν"],
  },
  {
    id: "inquiries-send-rental",
    question: "Πώς στέλνω αίτημα μίσθωσης;",
    answer:
      "1. Άνοιξε μηνιαία αγγελία.\n2. Επίλεξε μήνα έναρξης και διάρκεια.\n3. Γράψε μήνυμα στον ιδιοκτήτη.\n4. Πάτησε «Στείλε αίτημα μίσθωσης».\n\nΗ τελική συμφωνία γίνεται απευθείας με τον ιδιοκτήτη.",
    category: "inquiries",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    relatedFeature: "inquiry",
    priority: 95,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["μισθωση", "μηνιαι", "rental"],
  },
  {
    id: "inquiries-message-tips",
    question: "Τι πρέπει να γράψω στο μήνυμα προς τον ιδιοκτήτη;",
    answer:
      "Γράψε σύντομα: ποιος είσαι, πόσα άτομα, ημερομηνίες, ειδικές ανάγκες (π.χ. κατοικίδια, check-in). Όσο πιο συγκεκριμένο, τόσο πιο γρήγορη απάντηση.",
    category: "inquiries",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 80,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["μηνυμα", "message", "τι γραψ"],
  },
  {
    id: "inquiries-without-dates",
    question: "Μπορώ να στείλω μήνυμα χωρίς ημερομηνίες;",
    answer:
      "Ναι. Μπορείς να στείλεις αίτημα χωρίς να έχεις επιλέξει ημερομηνίες — γράψε στο μήνυμα ποιες ημερομηνίες σε ενδιαφέρουν. Με ημερομηνίες, ο ιδιοκτήτης βλέπει αμέσως το ενδιαφέρον σου.",
    category: "inquiries",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 75,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["χωρις ημερομην", "dates"],
  },
  {
    id: "inquiries-owner-response-time",
    question: "Πότε απαντά ο ιδιοκτήτης;",
    answer:
      "Ο χρόνος απάντησης εξαρτάται από τον ιδιοκτήτη. Θα λάβεις ειδοποίηση όταν απαντήσει μέσα από το Midora. Αν δεν απαντήσει σε λίγες ημέρες, δοκίμασε ξανά ή στείλε αίτημα σε άλλη αγγελία.",
    category: "inquiries",
    audience: "visitor",
    relatedRoutes: [...R],
    priority: 70,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["απαντ", "response", "ποτε"],
  },
  {
    id: "inquiries-where-messages",
    question: "Πού βλέπω τα μηνύματά μου;",
    answer:
      "Αν είσαι συνδεδεμένος, δες τα αιτήματα και τις απαντήσεις από το Dashboard → Αιτήματα/Μηνύματα. Κάθε συζήτηση συνδέεται με την αγγελία που σε ενδιέφερε.",
    category: "inquiries",
    audience: "all",
    relatedRoutes: ["/dashboard/", "/listings/"],
    priority: 85,
    quickSuggestion: false,
    suggestionContexts: ["owner_messages"],
    keywords: ["μηνυμα", "messages", "που βλεπ"],
  },
  {
    id: "inquiries-contact-cohost",
    question: "Μπορώ να επικοινωνήσω με συνοικοδεσπότη;",
    answer:
      "Ναι, αν ο ιδιοκτήτης έχει ορίσει συνοικοδεσπότη με δικαίωμα μηνυμάτων, μπορεί να απαντήσει στο αίτημά σου. Η επικοινωνία γίνεται μέσα από το Midora — όχι εκτός πλατφόρμας.",
    category: "inquiries",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 65,
    quickSuggestion: false,
    suggestionContexts: ["public_listing", "owner_messages"],
    keywords: ["συνοικοδεσποτ", "cohost"],
  },
  {
    id: "inquiries-no-phone",
    question: "Γιατί δεν εμφανίζεται τηλέφωνο ιδιοκτήτη;",
    answer:
      "Για ασφάλεια, το τηλέφωνο δεν εμφανίζεται πάντα δημόσια. Ο ιδιοκτήτης μπορεί να το κοινοποιήσει μετά το αίτημα, ανάλογα με τις ρυθμίσεις του (π.χ. μετά από αίτημα ή δημόσια).",
    category: "inquiries",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 78,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["τηλεφων", "phone", "επικοινων"],
  },
  {
    id: "inquiries-contact-when",
    question: "Πότε εμφανίζονται στοιχεία επικοινωνίας;",
    answer:
      "Εξαρτάται από τις ρυθμίσεις του ιδιοκτήτη: ιδιωτικά, μετά από αίτημα ή δημόσια. Συνήθως λεπτομέρειες επικοινωνίας μοιράζονται αφού στείλεις αίτημα και υπάρξει απάντηση.",
    category: "inquiries",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 72,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["στοιχεια", "επικοινων", "contact"],
  },
  {
    id: "inquiries-cancel-change",
    question: "Μπορώ να ακυρώσω ή να αλλάξω αίτημα;",
    answer:
      "Μπορείς να στείλεις νέο μήνυμα στην ίδια συζήτηση με ενημερωμένες ημερομηνίες ή να εξηγήσεις ότι δεν σε ενδιαφέρει πλέον. Δεν υπάρχει αυτόματη «ακύρωση κράτησης» — το Midora δεν διαχειρίζεται κρατήσεις.",
    category: "inquiries",
    audience: "visitor",
    relatedRoutes: ["/listings/", "/dashboard/"],
    priority: 60,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["ακυρω", "αλλαγ", "cancel"],
  },
  {
    id: "inquiries-no-response",
    question: "Τι κάνω αν ο ιδιοκτήτης δεν απαντά;",
    answer:
      "1. Περίμενε 1–2 ημέρες.\n2. Στείλε ευγενικό follow-up στο ίδιο αίτημα.\n3. Δοκίμασε παρόμοια αγγελία.\n4. Αν υπάρχει εξωτερικός σύνδεσμος, μπορείς να δεις την αγγελία και αλλού.",
    category: "inquiries",
    audience: "visitor",
    relatedRoutes: [...R],
    priority: 68,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["δεν απαντ", "no response"],
  },
  {
    id: "inquiries-multiple-listings",
    question: "Μπορώ να στείλω το ίδιο αίτημα σε περισσότερα ακίνητα;",
    answer:
      "Ναι. Κάθε αγγελία έχει ξεχωριστό αίτημα — άνοιξε κάθε αγγελία και στείλε αίτημα ξεχωριστά. Έτσι κάθε ιδιοκτήτης βλέπει μόνο το δικό του αίτημα.",
    category: "inquiries",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 55,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["πολλα", "multiple", "ακινητα"],
  },
  {
    id: "inquiries-owner-reply",
    question: "Πώς απαντάω σε αίτημα;",
    answer:
      "1. Άνοιξε την αγγελία → καρτέλα Αιτήματα.\n2. Επίλεξε το αίτημα επισκέπτη.\n3. Γράψε την απάντησή σου στο πεδίο μηνύματος.\n4. Αποστολή.\n\nΗ επικοινωνία μένει μέσα στο Midora μέχρι να συμφωνήσετε.",
    category: "inquiries",
    audience: "owner",
    relatedRoutes: ["/dashboard/listings/"],
    priority: 98,
    quickSuggestion: true,
    suggestionContexts: ["owner_messages"],
    keywords: ["απαντ", "reply", "αιτημα"],
    actionLinks: [{ label: "Αιτήματα", href: "/dashboard/listings/{id}/inquiries" }],
  },
  {
    id: "inquiries-message-templates",
    question: "Πώς χρησιμοποιώ πρότυπα μηνυμάτων;",
    answer:
      "Στο thread αιτήματος, γράψε την απάντησή σου στο πεδίο μηνύματος. Αν χρειάζεσαι επαναλαμβανόμενες φράσεις, κράτα δικές σου σημειώσεις — τα έτοιμα πρότυπα μηνυμάτων δεν είναι ακόμα διαθέσιμα στο Midora.",
    category: "inquiries",
    audience: "owner",
    relatedRoutes: ["/dashboard/listings/"],
    priority: 85,
    quickSuggestion: true,
    suggestionContexts: ["owner_messages"],
    keywords: ["προτυπ", "template", "μηνυμα"],
    actionLinks: [{ label: "Αιτήματα", href: "/dashboard/listings/{id}/inquiries" }],
  },
  {
    id: "inquiries-cohost-can-reply",
    question: "Μπορεί να απαντήσει συνοικοδεσπότης;",
    answer:
      "Ναι, αν ο ιδιοκτήτης του έχει δώσει δικαίωμα μηνυμάτων. Ο συνοικοδεσπότης απαντά από την ίδια καρτέλα Αιτήματα, χωρίς να αλλάζει την ιδιοκτησία της αγγελίας.",
    category: "inquiries",
    audience: "all",
    relatedRoutes: ["/dashboard/listings/", "/listings/"],
    priority: 88,
    quickSuggestion: true,
    suggestionContexts: ["owner_messages", "public_listing"],
    keywords: ["συνοικοδεσποτ", "cohost", "απαντ"],
  },
];
