import type { FaqItem } from "@/lib/assistant/faq-types";

const R = ["/dashboard", "/dashboard/listings"] as const;
const RW = ["/dashboard/listings/"] as const;

export const FAQ_OWNER_DASHBOARD: FaqItem[] = [
  {
    id: "owner-dashboard-all-listings",
    question: "Πού βλέπω όλες τις αγγελίες μου;",
    answer:
      "Πήγαινε στο Dashboard → Τα ακίνητά μου (/dashboard/listings). Εκεί βλέπεις όλες τις αγγελίες σου σε cards ή λίστα, με status και γρήγορες ενέργειες.",
    category: "owner_dashboard",
    audience: "owner",
    relatedRoutes: [...R],
    priority: 100,
    quickSuggestion: false,
    suggestionContexts: ["owner_dashboard"],
    keywords: ["αγγελιες", "listings", "που"],
    actionLinks: [{ label: "Αγγελίες μου", href: "/dashboard/listings" }],
  },
  {
    id: "owner-dashboard-back-to-listings",
    question: "Πώς επιστρέφω στις αγγελίες μου;",
    answer:
      "Πάτησε «Τα ακίνητά μου» στο πάνω μενού ή πήγαινε στο /dashboard/listings. Από workspace αγγελίας, χρησιμοποίησε το breadcrumb ή το logo.",
    category: "owner_dashboard",
    audience: "owner",
    relatedRoutes: [...R, ...RW],
    priority: 85,
    quickSuggestion: false,
    suggestionContexts: ["owner_listing_workspace"],
    keywords: ["επιστροφ", "back", "listings"],
    actionLinks: [{ label: "Αγγελίες μου", href: "/dashboard/listings" }],
  },
  {
    id: "owner-dashboard-open-listing",
    question: "Πώς ανοίγω μια συγκεκριμένη αγγελία;",
    answer:
      "Από /dashboard/listings, πάτησε την κάρτα της αγγελίας. Ανοίγει το workspace με καρτέλες: Επισκόπηση, Καταχώριση, Φωτογραφίες, Διαθεσιμότητα, Αιτήματα, Δημοσίευση κ.λπ.",
    category: "owner_dashboard",
    audience: "owner",
    relatedRoutes: [...R, ...RW],
    priority: 95,
    quickSuggestion: false,
    suggestionContexts: ["owner_dashboard"],
    keywords: ["ανοιγ", "open", "workspace"],
  },
  {
    id: "owner-dashboard-inquiries-where",
    question: "Πού βλέπω τα αιτήματα;",
    answer:
      "Άνοιξε την αγγελία → καρτέλα Αιτήματα. Εκεί βλέπεις αιτήματα διαθεσιμότητας/μίσθωσης από επισκέπτες και μπορείς να απαντήσεις.",
    category: "owner_dashboard",
    audience: "owner",
    relatedRoutes: [...RW],
    priority: 92,
    quickSuggestion: false,
    suggestionContexts: ["owner_dashboard", "owner_messages"],
    keywords: ["αιτημα", "inquiries", "requests"],
    actionLinks: [{ label: "Αιτήματα", href: "/dashboard/listings/{id}/inquiries" }],
  },
  {
    id: "owner-dashboard-messages-where",
    question: "Πού βλέπω τα μηνύματα;",
    answer:
      "Τα μηνύματα συνδέονται με αιτήματα. Άνοιξε την αγγελία → Αιτήματα ή το γενικό Dashboard → Μηνύματα (αν υπάρχει). Κάθε thread αντιστοιχεί σε αίτημα επισκέπτη.",
    category: "owner_dashboard",
    audience: "owner",
    relatedRoutes: [...RW, "/dashboard"],
    priority: 90,
    quickSuggestion: true,
    suggestionContexts: ["owner_messages"],
    keywords: ["μηνυμα", "messages"],
    actionLinks: [{ label: "Αιτήματα", href: "/dashboard/listings/{id}/inquiries" }],
  },
  {
    id: "owner-dashboard-analytics",
    question: "Πού βλέπω τα στατιστικά;",
    answer:
      "Άνοιξε την αγγελία → καρτέλα Στατιστικά (Analytics). Εκεί βλέπεις προβολές και ενδείξεις απόδοσης, ανάλογα με τα διαθέσιμα δεδομένα.",
    category: "owner_dashboard",
    audience: "owner",
    relatedRoutes: [...RW],
    priority: 70,
    quickSuggestion: false,
    suggestionContexts: ["owner_listing_workspace"],
    keywords: ["στατιστικ", "analytics", "views"],
    actionLinks: [{ label: "Στατιστικά", href: "/dashboard/listings/{id}/analytics" }],
  },
  {
    id: "owner-dashboard-completion-score",
    question: "Τι σημαίνει βαθμός πληρότητας αγγελίας;",
    answer:
      "Δείχνει πόσο ολοκληρωμένη είναι η αγγελία (φωτογραφίες, περιγραφή, τιμές, παροχές κ.λπ.). Υψηλότερη πληρότητα βοηθά τους επισκέπτες να εμπιστευτούν την αγγελία.",
    category: "owner_dashboard",
    audience: "owner",
    relatedRoutes: [...R, ...RW],
    priority: 78,
    quickSuggestion: false,
    suggestionContexts: ["owner_dashboard", "owner_listing_workspace"],
    keywords: ["πληροτητα", "completion", "score"],
  },
  {
    id: "owner-dashboard-improve-listing",
    question: "Πώς βελτιώνω την αγγελία μου;",
    answer:
      "1. Πρόσθεσε ποιοτικές φωτογραφίες και εξώφυλλο.\n2. Συμπλήρωσε παροχές και περιγραφή.\n3. Όρισε σωστές τιμές και διαθεσιμότητα.\n4. Απάντα γρήγορα στα αιτήματα.\n5. Δημοσίευσε όταν πληρούνται οι προϋποθέσεις.",
    category: "owner_dashboard",
    audience: "owner",
    relatedRoutes: [...RW],
    priority: 82,
    quickSuggestion: true,
    suggestionContexts: ["owner_dashboard", "owner_listing_workspace"],
    keywords: ["βελτιω", "improve", "tips"],
  },
  {
    id: "owner-dashboard-published-status",
    question: "Πού βλέπω αν η αγγελία είναι δημοσιευμένη;",
    answer:
      "Στη λίστα αγγελιών (/dashboard/listings) βλέπεις status (π.χ. ενεργή, πρόχειρη, σε έλεγχο). Λεπτομέρειες και κουμπί δημοσίευσης στην καρτέλα Δημοσίευση.",
    category: "owner_dashboard",
    audience: "owner",
    relatedRoutes: [...R, ...RW],
    priority: 88,
    quickSuggestion: false,
    suggestionContexts: ["owner_dashboard"],
    keywords: ["δημοσιευ", "published", "status"],
    actionLinks: [{ label: "Δημοσίευση", href: "/dashboard/listings/{id}/publish" }],
  },
  {
    id: "owner-dashboard-preview-public",
    question: "Πώς βλέπω την αγγελία όπως τη βλέπει ο επισκέπτης;",
    answer:
      "Από το workspace, πάτησε «Προβολή δημόσιας αγγελίας» ή άνοιξε το public link (/listings/{id}). Έτσι βλέπεις ακριβώς τι εμφανίζεται στους επισκέπτες.",
    category: "owner_dashboard",
    audience: "owner",
    relatedRoutes: [...RW, "/listings/"],
    priority: 80,
    quickSuggestion: false,
    suggestionContexts: ["owner_listing_workspace"],
    keywords: ["προβολ", "preview", "public"],
  },
  {
    id: "owner-dashboard-mobile-preview",
    question: "Πώς αλλάζω από προβολή υπολογιστή σε κινητό;",
    answer:
      "Στο workspace ή preview, χρησιμοποίησε το toggle Desktop/Mobile (αν διαθέσιμο) ή σμίκρυνε το παράθυρο browser. Για πλήρη έλεγχο, άνοιξε τη δημόσια αγγελία από κινητό.",
    category: "owner_dashboard",
    audience: "owner",
    relatedRoutes: [...RW],
    priority: 55,
    quickSuggestion: false,
    suggestionContexts: ["owner_listing_workspace"],
    keywords: ["mobile", "κινητο", "preview"],
  },
  {
    id: "owner-dashboard-update-listing",
    question: "Πώς ενημερώνω την αγγελία μου;",
    answer:
      "Άνοιξε την αγγελία από /dashboard/listings και επεξεργάσου την κατάλληλη καρτέλα (Καταχώριση, Φωτογραφίες, Διαθεσιμότητα). Πάτησε Αποθήκευση σε κάθε ενότητα. Οι αλλαγές εμφανίζονται δημόσια μετά την αποθήκευση.",
    category: "owner_dashboard",
    audience: "owner",
    relatedRoutes: [...RW],
    priority: 93,
    quickSuggestion: true,
    suggestionContexts: ["owner_dashboard", "owner_listing_workspace"],
    keywords: ["ενημερω", "update", "edit"],
    actionLinks: [{ label: "Καταχώριση", href: "/dashboard/listings/{id}/edit" }],
  },
];
