import type { FaqItem } from "@/lib/assistant/faq-types";
import { buildAadeOwnerGuideHelpContent } from "@/lib/aade-owner-guide";
import {
  AADE_GENERAL_DISCLAIMER,
  AADE_SHORT_DISCLAIMER,
  ASSISTANT_AADE_SAFE_REPLY,
  DAMAGE_FAQ_ANSWER,
  DAMAGE_FAQ_QUESTION,
  MIDORA_ROLE_FULL,
} from "@/lib/midora-legal-copy";

/**
 * Legal role, AADE guidance, and damage responsibility FAQs.
 * Damage = FAQ/Terms copy only — no incident/claim product.
 */
export const FAQ_LEGAL_AADE: FaqItem[] = [
  {
    id: "legal-midora-role",
    question: "Τι ρόλο έχει το Midora στις μισθώσεις;",
    answer: MIDORA_ROLE_FULL,
    category: "safety",
    audience: "all",
    relatedRoutes: ["/terms", "/help", "/listings/", "/dashboard/"],
    priority: 100,
    quickSuggestion: true,
    suggestionLabel: "Ρόλος Midora",
    suggestionContexts: ["home", "public_listing", "owner_dashboard"],
    keywords: ["ρολος", "midora", "πλατφορμα", "κρατηση", "πληρωμ"],
    aliases: ["Τι είναι το Midora;", "Κάνει κρατήσεις το Midora;"],
  },
  {
    id: "legal-aade-owner-guide",
    question: "Οδηγός ΑΑΔΕ για ιδιοκτήτες",
    answer: buildAadeOwnerGuideHelpContent(),
    category: "owner_listing",
    audience: "owner",
    relatedRoutes: ["/dashboard/", "/help", "/listing-rules", "/short-term-rental-guide"],
    priority: 97,
    quickSuggestion: true,
    suggestionLabel: "Οδηγός ΑΑΔΕ",
    suggestionContexts: ["owner_dashboard", "owner_listing_workspace"],
    keywords: [
      "ααδε",
      "aade",
      "αμα",
      "εσλ",
      "μαγ",
      "οδηγος",
      "δηλωση",
      "βραχυχρον",
      "μηνιαι",
    ],
    aliases: [
      "Πού βρίσκω ΑΜΑ ΕΣΛ ΜΑΓ;",
      "Πώς δηλώνω διαμονή στην ΑΑΔΕ;",
      "Οδηγός ΑΑΔΕ Midora",
    ],
  },
  {
    id: "legal-aade-platform-field",
    question:
      "Τι επιλέγω στην ΑΑΔΕ αν η συμφωνία προήλθε από το Midora;",
    answer: [
      "Αν η συμφωνία προήλθε από αγγελία στο Midora και η εφαρμογή της ΑΑΔΕ ζητά ηλεκτρονική πλατφόρμα, μπορεί να υπάρχει διαθέσιμη επιλογή όπως «Άλλες ψηφιακές πλατφόρμες», όπου ο ιδιοκτήτης μπορεί να αναφέρει το Midora, σύμφωνα με όσα επιτρέπει η εφαρμογή.",
      "",
      "Μην επιλέγεις Airbnb, Booking.com, Vrbo ή άλλη πλατφόρμα αν η συγκεκριμένη συμφωνία δεν προήλθε από εκεί.",
      "",
      "Το Midora δεν υποβάλλει τη δήλωση για λογαριασμό σου και δεν παρέχει φορολογική, λογιστική ή νομική συμβουλή. Για τη σωστή συμπλήρωση, συμβουλεύσου λογιστή ή την ΑΑΔΕ.",
      "",
      AADE_GENERAL_DISCLAIMER,
    ].join("\n"),
    category: "owner_listing",
    audience: "owner",
    relatedRoutes: ["/dashboard/", "/help", "/listing-rules"],
    priority: 96,
    quickSuggestion: true,
    suggestionLabel: "ΑΑΔΕ και Midora",
    suggestionContexts: ["owner_dashboard", "owner_listing_workspace"],
    keywords: ["ααδε", "aade", "πλατφορμα", "αλλες ψηφιακ", "δηλωση"],
    aliases: [
      "Πώς δηλώνω το Midora στην ΑΑΔΕ;",
      "Άλλες ψηφιακές πλατφόρμες ΑΑΔΕ",
    ],
  },
  {
    id: "legal-aade-short-term-phone",
    question:
      "Αν ο ενδιαφερόμενος με βρήκε από το Midora αλλά συμφωνήσαμε τηλεφωνικά, πώς το δηλώνω στην ΑΑΔΕ;",
    answer: [
      "Αν πρόκειται για βραχυχρόνια διαμονή, ο ιδιοκτήτης ή διαχειριστής του ακινήτου υποβάλλει Δήλωση Βραχυχρόνιας Διαμονής στην εφαρμογή της ΑΑΔΕ για τη Βραχυχρόνια Μίσθωση Ακινήτων.",
      "",
      "Γενικά βήματα:",
      "1. Συνδέεσαι στο myAADE.",
      "2. Ανοίγεις την εφαρμογή Βραχυχρόνια Μίσθωση Ακινήτων.",
      "3. Επιλέγεις το ακίνητο / ΑΜΑ που αντιστοιχεί στην αγγελία.",
      "4. Συμπληρώνεις τα στοιχεία διαμονής, όπως ημερομηνίες άφιξης και αναχώρησης, στοιχεία μισθωτή και συμφωνημένο ποσό, σύμφωνα με όσα ζητά η εφαρμογή.",
      "5. Αν η εφαρμογή ζητά ηλεκτρονική πλατφόρμα και η συμφωνία προήλθε από το Midora, μπορεί να υπάρχει επιλογή όπως «Άλλες ψηφιακές πλατφόρμες», όπου μπορείς να αναφέρεις το Midora, σύμφωνα με όσα επιτρέπει η εφαρμογή.",
      "6. Υποβάλλεις τη δήλωση και κρατάς το αποδεικτικό υποβολής.",
      "",
      "Το ότι η πληρωμή έγινε απευθείας μεταξύ των μερών, ακόμη και με μετρητά, δεν σημαίνει ότι η μίσθωση δεν δηλώνεται. Το Midora δεν υποβάλλει τη δήλωση για λογαριασμό σου.",
      "",
      AADE_SHORT_DISCLAIMER,
    ].join("\n"),
    category: "owner_listing",
    audience: "owner",
    relatedRoutes: ["/dashboard/", "/help", "/short-term-rental-guide"],
    priority: 94,
    quickSuggestion: false,
    suggestionContexts: ["owner_dashboard", "owner_listing_workspace"],
    keywords: ["ααδε", "τηλεφων", "βραχυχρον", "δηλωση", "myaade"],
  },
  {
    id: "legal-aade-monthly",
    question: "Τι κάνω αν η συμφωνία είναι μηνιαία ή μακροχρόνια;",
    answer: [
      "Αν η συμφωνία αφορά μηνιαία ή μακροχρόνια μίσθωση, δεν πρόκειται για Δήλωση Βραχυχρόνιας Διαμονής. Ο ιδιοκτήτης ακολουθεί τη διαδικασία ηλεκτρονικής υποβολής μισθωτηρίου στην ΑΑΔΕ, όπου απαιτείται.",
      "",
      "Γενικά βήματα:",
      "1. Συνδέεσαι στο myAADE.",
      "2. Ανοίγεις την εφαρμογή Δηλώσεις Μίσθωσης Ακινήτων / Στοιχεία Μισθώσεων Ακίνητης Περιουσίας.",
      "3. Συμπληρώνεις στοιχεία εκμισθωτή και μισθωτή.",
      "4. Συμπληρώνεις στοιχεία ακινήτου, διάρκεια μίσθωσης και συμφωνημένο μίσθωμα, σύμφωνα με όσα ζητά η εφαρμογή.",
      "5. Υποβάλλεις τη δήλωση και κρατάς το αποδεικτικό υποβολής.",
      "",
      "Το Midora δεν υποβάλλει μισθωτήρια ή φορολογικές δηλώσεις για λογαριασμό ιδιοκτητών.",
      "",
      AADE_SHORT_DISCLAIMER,
    ].join("\n"),
    category: "owner_listing",
    audience: "owner",
    relatedRoutes: ["/dashboard/", "/help"],
    priority: 92,
    quickSuggestion: false,
    suggestionContexts: ["owner_dashboard", "owner_listing_workspace"],
    keywords: ["μηνιαι", "μακροχρον", "μισθωτηρ", "ααδε", "φορολογ"],
  },
  {
    id: "legal-damage-responsibility",
    question: DAMAGE_FAQ_QUESTION,
    answer: DAMAGE_FAQ_ANSWER,
    category: "safety",
    audience: "all",
    relatedRoutes: ["/terms", "/help", "/listings/"],
    priority: 90,
    quickSuggestion: false,
    suggestionContexts: ["public_listing", "owner_dashboard"],
    keywords: ["ζημια", "φθορα", "αποζημιωση", "ασφαλιση", "damage"],
    aliases: ["Ποιος πληρώνει για ζημιές;", "Υπάρχει προστασία ζημιών;"],
  },
  {
    id: "legal-aade-assistant-pattern",
    question: "Το Midora υποβάλλει δηλώσεις στην ΑΑΔΕ;",
    answer: ASSISTANT_AADE_SAFE_REPLY,
    category: "owner_listing",
    audience: "owner",
    relatedRoutes: ["/help", "/dashboard/"],
    priority: 98,
    quickSuggestion: true,
    suggestionLabel: "Δηλώσεις ΑΑΔΕ",
    suggestionContexts: ["owner_dashboard", "owner_listing_workspace"],
    keywords: ["ααδε", "υποβαλλει", "δηλωση", "φορολογ"],
  },
];
