import type { FaqItem } from "@/lib/assistant/faq-types";

const R = ["/dashboard/profile"] as const;

export const FAQ_PROFILE: FaqItem[] = [
  {
    id: "profile-change-photo",
    question: "Πώς αλλάζω φωτογραφία προφίλ;",
    answer:
      "1. Πήγαινε στο Dashboard → Προφίλ (/dashboard/profile).\n2. Πάτησε στην τρέχουσα φωτογραφία ή στο κουμπί επεξεργασίας.\n3. Ανέβασε νέα εικόνα.\n4. Αποθήκευσε.",
    category: "profile",
    audience: "all",
    relatedRoutes: [...R],
    priority: 90,
    quickSuggestion: false,
    suggestionContexts: ["owner_profile"],
    keywords: ["φωτογραφ", "avatar", "photo"],
    actionLinks: [{ label: "Προφίλ", href: "/dashboard/profile" }],
  },
  {
    id: "profile-change-name",
    question: "Πώς αλλάζω όνομα;",
    answer:
      "Στο /dashboard/profile, επεξεργάσου το πεδίο ονόματος και αποθήκευσε. Αν συνδέθηκες με Google, το όνομα μπορεί να συγχρονιστεί — μπορείς να το προσαρμόσεις στο προφίλ.",
    category: "profile",
    audience: "all",
    relatedRoutes: [...R],
    priority: 88,
    quickSuggestion: false,
    suggestionContexts: ["owner_profile"],
    keywords: ["ονομα", "name", "google"],
    actionLinks: [{ label: "Προφίλ", href: "/dashboard/profile" }],
  },
  {
    id: "profile-add-bio",
    question: "Πώς προσθέτω περιγραφή στο προφίλ;",
    answer:
      "Στο Dashboard → Προφίλ, συμπλήρωσε το πεδίο βιογραφίας/περιγραφής. Αυτό εμφανίζεται στο δημόσιο προφίλ σου ως ιδιοκτήτης, αν είναι ενεργό.",
    category: "profile",
    audience: "owner",
    relatedRoutes: [...R],
    priority: 82,
    quickSuggestion: false,
    suggestionContexts: ["owner_profile"],
    keywords: ["βιο", "bio", "περιγραφ"],
    actionLinks: [{ label: "Προφίλ", href: "/dashboard/profile" }],
  },
  {
    id: "profile-add-languages",
    question: "Πώς προσθέτω γλώσσες;",
    answer:
      "Στο προφίλ (/dashboard/profile), επίλεξε τις γλώσσες που μιλάς. Εμφανίζονται στο δημόσιο προφίλ ώστε οι επισκέπτες να ξέρουν πώς να επικοινωνήσουν.",
    category: "profile",
    audience: "all",
    relatedRoutes: [...R],
    priority: 75,
    quickSuggestion: false,
    suggestionContexts: ["owner_profile"],
    keywords: ["γλωσσ", "languages"],
    actionLinks: [{ label: "Προφίλ", href: "/dashboard/profile" }],
  },
  {
    id: "profile-change-email",
    question: "Πώς αλλάζω email;",
    answer:
      "Το email συνδέεται με τον λογαριασμό σου (π.χ. Google ή email login). Για αλλαγή, δες τις ρυθμίσεις λογαριασμού στο προφίλ ή επικοινώνησε με υποστήριξη αν δεν μπορείς.",
    category: "profile",
    audience: "all",
    relatedRoutes: [...R],
    priority: 70,
    quickSuggestion: false,
    suggestionContexts: ["owner_profile"],
    keywords: ["email", "λογαριασμ"],
  },
  {
    id: "profile-change-phone",
    question: "Πώς αλλάζω τηλέφωνο;",
    answer:
      "Στο /dashboard/profile, ενημέρωσε το τηλέφωνο και ολοκλήρωσε επαλήθευση αν ζητηθεί. Το τηλέφωνο μπορεί να εμφανίζεται δημόσια ή μόνο μετά από αίτημα, ανάλογα με τις ρυθμίσεις.",
    category: "profile",
    audience: "all",
    relatedRoutes: [...R],
    priority: 78,
    quickSuggestion: false,
    suggestionContexts: ["owner_profile"],
    keywords: ["τηλεφων", "phone", "verify"],
    actionLinks: [{ label: "Προφίλ", href: "/dashboard/profile" }],
  },
  {
    id: "profile-public-fields",
    question: "Ποια στοιχεία φαίνονται δημόσια;",
    answer:
      "Συνήθως: όνομα, φωτογραφία, βιογραφία, γλώσσες, ενεργές αγγελίες. Δεν εμφανίζονται ιδιωτικά στοιχεία άλλων χρηστών (π.χ. email) χωρίς ρητή κοινοποίηση.",
    category: "profile",
    audience: "all",
    relatedRoutes: [...R, "/listings/"],
    priority: 85,
    quickSuggestion: false,
    suggestionContexts: ["owner_profile", "public_listing"],
    keywords: ["δημοσια", "public", "στοιχεια"],
  },
  {
    id: "profile-private-fields",
    question: "Ποια στοιχεία είναι ιδιωτικά;",
    answer:
      "Email λογαριασμού, εσωτερικές ρυθμίσεις και στοιχεία που δεν έχεις επιλέξει για δημόσια εμφάνιση παραμένουν ιδιωτικά. Τηλέφωνο μπορεί να είναι ιδιωτικό ή μετά από αίτημα.",
    category: "profile",
    audience: "all",
    relatedRoutes: [...R],
    priority: 72,
    quickSuggestion: false,
    suggestionContexts: ["owner_profile"],
    keywords: ["ιδιωτικ", "private"],
  },
  {
    id: "profile-view-public",
    question: "Πώς βλέπω το δημόσιο προφίλ μου;",
    answer:
      "Από το προφίλ ή από μια αγγελία σου, άνοιξε «Προβολή δημόσιου προφίλ» ή το link /profile/{username} (αν διαθέσιμο). Έτσι βλέπεις τι βλέπουν οι επισκέπτες.",
    category: "profile",
    audience: "owner",
    relatedRoutes: [...R],
    priority: 80,
    quickSuggestion: false,
    suggestionContexts: ["owner_profile"],
    keywords: ["δημοσιο προφιλ", "preview", "public profile"],
  },
  {
    id: "profile-as-owner",
    question: "Πώς εμφανίζομαι ως ιδιοκτήτης;",
    answer:
      "Συμπλήρωσε προφίλ (όνομα, φωτο, βιο, γλώσσες) και δημοσίευσε αγγελίες. Στις αγγελίες σου εμφανίζεσαι ως ιδιοκτήτης/οικοδεσπότης με link στο δημόσιο προφίλ.",
    category: "profile",
    audience: "owner",
    relatedRoutes: [...R, "/dashboard/listings"],
    priority: 83,
    quickSuggestion: false,
    suggestionContexts: ["owner_profile", "owner_dashboard"],
    keywords: ["ιδιοκτητ", "owner", "εμφανιζ"],
  },
  {
    id: "profile-as-cohost",
    question: "Πώς εμφανίζομαι ως συνοικοδεσπότης;",
    answer:
      "Αποδέχεσαι πρόσκληση συνοικοδεσπότη από ιδιοκτήτη. Αν ο ιδιοκτήτης σε εμφανίζει δημόσια, μπορεί να φαίνεσαι στην αγγελία. Το προφίλ σου χρησιμοποιεί τα ίδια στοιχεία από /dashboard/profile.",
    category: "profile",
    audience: "cohost",
    relatedRoutes: [...R, "/dashboard/listings/"],
    priority: 68,
    quickSuggestion: false,
    suggestionContexts: ["owner_profile"],
    keywords: ["συνοικοδεσποτ", "cohost"],
  },
];
