import type { FaqItem } from "@/lib/assistant/faq-types";

export const FAQ_SAFETY: FaqItem[] = [
  {
    id: "safety-communicate-in-midora",
    question: "Είναι ασφαλές να επικοινωνώ μέσα από το Midora;",
    answer:
      "Για την ασφάλειά σου, επικοινώνησε μέσα από το Midora και επιβεβαίωσε τη διαθεσιμότητα πριν από οποιαδήποτε συμφωνία. Έτσι έχεις ιστορικό αιτημάτων και απαντήσεων.",
    category: "safety",
    audience: "all",
    relatedRoutes: ["/listings/", "/dashboard/"],
    priority: 95,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["ασφαλ", "safe", "επικοινων"],
  },
  {
    id: "safety-midora-payments",
    question: "Το Midora διαχειρίζεται πληρωμές;",
    answer:
      "Όχι. Το Midora δεν επεξεργάζεται πληρωμές, κρατήσεις ή refunds. Στέλνεις αίτημα, επικοινωνείς με τον ιδιοκτήτη και συμφωνείτε απευθείας — εκτός πλατφόρμας για πληρωμή.",
    category: "safety",
    audience: "all",
    relatedRoutes: ["/listings/", "/dashboard/"],
    priority: 100,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["πληρωμ", "payment", "refund"],
  },
  {
    id: "safety-pay-before-talk",
    question: "Πρέπει να στείλω χρήματα πριν μιλήσω με τον ιδιοκτήτη;",
    answer:
      "Όχι — μην στέλνεις χρήματα πριν επιβεβαιώσεις διαθεσιμότητα και όρους με τον ιδιοκτήτη. Το Midora δεν εγγυάται πληρωμές. Για την ασφάλειά σου, επικοινώνησε μέσα από το Midora πρώτα.",
    category: "safety",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 98,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["χρηματα", "money", "προκαταβολ"],
  },
  {
    id: "safety-suspicious-listing",
    question: "Τι κάνω αν μια αγγελία φαίνεται ύποπτη;",
    answer:
      "Μην στείλεις χρήματα εκτός Midora. Στείλε αίτημα μέσα από την πλατφόρμα, έλεγξε προφίλ ιδιοκτήτη και εξωτερικούς συνδέσμους. Αν κάτι δεν σου φαίνεται σωστό, κάνε αναφορά ή επικοινώνησε με υποστήριξη.",
    category: "safety",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 88,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["υποπτο", "suspicious", "scam"],
  },
  {
    id: "safety-report-listing",
    question: "Πώς κάνω αναφορά αγγελίας;",
    answer:
      "Από την αγγελία ή τον Βοηθό Midora, στείλε αίτημα στην υποστήριξη με link αγγελίας και τι ακριβώς σε ανησυχεί. Η ομάδα Midora εξετάζει αναφορές.",
    category: "safety",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 75,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["αναφορα", "report"],
  },
  {
    id: "safety-no-exact-address",
    question: "Γιατί δεν εμφανίζεται ακριβής διεύθυνση;",
    answer:
      "Για προστασία ιδιωτικότητας, η δημόσια αγγελία δείχνει κατά προσέγγιση τοποθεσία. Η ακριβής διεύθυνση μοιράζεται απευθείας μετά από επικοινωνία και συμφωνία.",
    category: "safety",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 70,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["διευθυνση", "address", "ακριβ"],
  },
  {
    id: "safety-real-listing",
    question: "Πώς ξέρω ότι μια αγγελία είναι πραγματική;",
    answer:
      "Έλεγξε: πλήρες προφίλ ιδιοκτήτη, πολλές φωτογραφίες, ξεκάθαρη περιγραφή, εξωτερικό link (προαιρετικό), απάντηση σε αίτημα. Μην πληρώνεις πριν επιβεβαιώσεις διαθεσιμότητα.",
    category: "safety",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 82,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["πραγματικ", "real", "εμπιστοσυνη"],
  },
  {
    id: "safety-external-link-trust",
    question: "Τι σημαίνει εξωτερικός σύνδεσμος ως trust signal;",
    answer:
      "Αν ο ιδιοκτήτης έχει δημόσιο link σε Airbnb/Booking κ.λπ., δείχνει ότι η αγγελία υπάρχει και αλλού. Δεν αντικαθιστά επαλήθευση — απλά ενισχύει την εμπιστοσύνη.",
    category: "safety",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 65,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["trust", "εξωτερικ", "link"],
  },
  {
    id: "safety-last-updated",
    question: "Τι σημαίνει «τελευταία ενημέρωση αγγελίας»;",
    answer:
      "Δείχνει πότε ενημερώθηκε τελευταία η αγγελία από τον ιδιοκτήτη (π.χ. τιμές, φωτογραφίες). Πιο πρόσφατη ενημέρωση συνήθως σημαίνει πιο ενεργή διαχείριση.",
    category: "safety",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 58,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["ενημερωση", "updated", "τελευταια"],
  },
  {
    id: "safety-complete-owner-profile",
    question: "Τι σημαίνει συμπληρωμένο προφίλ ιδιοκτήτη;",
    answer:
      "Ιδιοκτήτης με όνομα, φωτογραφία, βιογραφία και γλώσσες — όχι κενό προφίλ. Βοηθά να ξέρεις με ποιον επικοινωνείς. Δεν εγγυάται από μόνο του ασφάλεια, αλλά είναι θετικό σήμα.",
    category: "safety",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 62,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["προφιλ", "profile", "συμπληρωμεν"],
  },
];
