import type { FaqItem } from "@/lib/assistant/faq-types";

const R = ["/listings/"] as const;

export const FAQ_PUBLIC_LISTING: FaqItem[] = [
  {
    id: "public-listing-photos-all",
    question: "Πώς βλέπω όλες τις φωτογραφίες ενός ακινήτου;",
    answer:
      "Στην κορυφή της αγγελίας βλέπεις gallery φωτογραφιών. Πάτησε σε φωτογραφία για μεγέθυνση ή άνοιγμα πλήρους gallery. Μπορείς να κάνεις scroll/βέλη για να δεις όλες.",
    category: "public_listing",
    audience: "visitor",
    relatedRoutes: [...R],
    relatedFeature: "gallery",
    priority: 95,
    quickSuggestion: true,
    suggestionContexts: ["public_listing"],
    suggestionLabel: "Πού βλέπω όλες τις φωτογραφίες;",
    keywords: ["φωτογραφ", "gallery", "εικον"],
    actionLinks: [{ label: "Προβολή αγγελίας", href: "/listings/" }],
  },
  {
    id: "public-listing-amenities-where",
    question: "Πού βλέπω τις παροχές του ακινήτου;",
    answer:
      "Σκρόλαρε στην αγγελία μέχρι την ενότητα «Παροχές» ή «Τι προσφέρει ο χώρος». Εκεί εμφανίζονται Wi-Fi, κλιματισμός, κουζίνα, parking κ.λπ. που έχει δηλώσει ο ιδιοκτήτης.",
    category: "public_listing",
    audience: "visitor",
    relatedRoutes: [...R],
    relatedFeature: "amenities",
    priority: 88,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["παροχ", "amenities", "wifi"],
  },
  {
    id: "public-listing-pets-where",
    question: "Πού βλέπω αν επιτρέπονται κατοικίδια;",
    answer:
      "Δες την ενότητα «Κανόνες» ή «Παροχές» στην αγγελία — εκεί αναφέρεται αν επιτρέπονται κατοικίδια. Μπορείς επίσης να το ρωτήσεις στο αίτημα προς τον ιδιοκτήτη.",
    category: "public_listing",
    audience: "visitor",
    relatedRoutes: [...R],
    priority: 92,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["κατοικιδ", "pets", "σκυλος"],
  },
  {
    id: "public-listing-location-where",
    question: "Πού βλέπω την περιοχή του ακινήτου;",
    answer:
      "Στην ενότητα «Τοποθεσία» βλέπεις χάρτη με κατά προσέγγιση σημείο και περιοχή/πόλη. Η ακριβής διεύθυνση δεν εμφανίζεται δημόσια για ασφάλεια.",
    category: "public_listing",
    audience: "visitor",
    relatedRoutes: [...R],
    relatedFeature: "map",
    priority: 80,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["τοποθεσ", "χαρτης", "περιοχ"],
  },
  {
    id: "public-listing-no-exact-address",
    question: "Γιατί δεν εμφανίζεται η ακριβής διεύθυνση;",
    answer:
      "Για την ασφάλεια ιδιοκτήτη και επισκεπτών, το Midora δείχνει κατά προσέγγιση τοποθεσία στον χάρτη. Η ακριβής διεύθυνση μοιράζεται απευθείας μετά από επικοινωνία και συμφωνία.",
    category: "public_listing",
    audience: "visitor",
    relatedRoutes: [...R],
    priority: 75,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["διευθυνση", "ακριβ", "address"],
  },
  {
    id: "public-listing-owner-profile",
    question: "Πώς βλέπω το προφίλ του ιδιοκτήτη;",
    answer:
      "Στην αγγελία, στην ενότητα «Ιδιοκτήτης» ή «Σχετικά με τον οικοδεσπότη», πάτησε το όνομα ή την εικόνα προφίλ για να ανοίξεις το δημόσιο προφίλ του.",
    category: "public_listing",
    audience: "visitor",
    relatedRoutes: [...R],
    relatedFeature: "owner_profile",
    priority: 90,
    quickSuggestion: true,
    suggestionContexts: ["public_listing"],
    suggestionLabel: "Πώς βλέπω το προφίλ ιδιοκτήτη;",
    keywords: ["προφιλ", "ιδιοκτητ", "owner"],
  },
  {
    id: "public-listing-cohost-what",
    question: "Τι είναι ο συνοικοδεσπότης;",
    answer:
      "Ο συνοικοδεσπότης είναι άτομο που βοηθά τον ιδιοκτήτη να διαχειρίζεται την αγγελία (π.χ. μηνύματα, διαθεσιμότητα), με δικαιώματα που ορίζει ο ιδιοκτήτης. Δεν αντικαθιστά τον ιδιοκτήτη.",
    category: "public_listing",
    audience: "visitor",
    relatedRoutes: [...R],
    priority: 65,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["συνοικοδεσποτ", "cohost"],
  },
  {
    id: "public-listing-approximate-location",
    question: "Τι σημαίνει ότι η τοποθεσία είναι κατά προσέγγιση;",
    answer:
      "Ο χάρτης δείχνει την γενική περιοχή, όχι την ακριβή είσοδο. Έτσι προστατεύονται τα προσωπικά στοιχεία μέχρι να επικοινωνήσεις με τον ιδιοκτήτη.",
    category: "public_listing",
    audience: "visitor",
    relatedRoutes: [...R],
    priority: 70,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["προσεγγιση", "approximate", "χαρτης"],
  },
  {
    id: "public-listing-parking-where",
    question: "Πού βλέπω αν υπάρχει parking;",
    answer:
      "Δες την ενότητα «Παροχές» — αν υπάρχει parking, εμφανίζεται εκεί. Μπορείς επίσης να χρησιμοποιήσεις φίλτρο parking στην αναζήτηση (/listings).",
    category: "public_listing",
    audience: "visitor",
    relatedRoutes: [...R],
    priority: 78,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["parking", "παρκιν", "θεση"],
  },
  {
    id: "public-listing-checkin-out",
    question: "Πού βλέπω check-in και check-out;",
    answer:
      "Στην αγγελία, στην ενότητα «Κανόνες» ή «Λεπτομέρειες διαμονής», εμφανίζονται ώρες check-in/check-out αν τις έχει ορίσει ο ιδιοκτήτης. Για ειδικές ανάγκες, ρώτα στο αίτημα.",
    category: "public_listing",
    audience: "visitor",
    relatedRoutes: [...R],
    priority: 72,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["checkin", "checkout", "αφιξη", "αναχωρηση"],
  },
  {
    id: "public-listing-kids-friendly",
    question: "Πού βλέπω αν το ακίνητο είναι κατάλληλο για παιδιά;",
    answer:
      "Δες τις παροχές και τους κανόνες στην αγγελία — κρεβάτια, ασφάλεια, κανόνες ησυχίας κ.λπ. Αν δεν αναφέρεται ρητά, ρώτα τον ιδιοκτήτη στο αίτημα.",
    category: "public_listing",
    audience: "visitor",
    relatedRoutes: [...R],
    priority: 60,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["παιδ", "kids", "οικογενεια"],
  },
  {
    id: "public-listing-external-platform",
    question: "Πού βλέπω αν η αγγελία υπάρχει και σε άλλη πλατφόρμα;",
    answer:
      "Αν ο ιδιοκτήτης έχει ενεργοποιήσει δημόσιο εξωτερικό σύνδεσμο, εμφανίζεται χαμηλά στην αγγελία (π.χ. Airbnb, Booking). Δεν είναι κράτηση μέσω Midora — απλά link προς άλλη πλατφόρμα.",
    category: "public_listing",
    audience: "visitor",
    relatedRoutes: [...R],
    relatedFeature: "external_links",
    priority: 85,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["airbnb", "booking", "εξωτερικ", "link"],
  },
];
