import type { FaqItem } from "@/lib/assistant/faq-types";

const R = ["/", "/listings"] as const;

export const FAQ_SEARCH: FaqItem[] = [
  {
    id: "search-how",
    question: "Πώς κάνω αναζήτηση στο Midora;",
    answer:
      "Πήγαινε στην Αναζήτηση (/listings) ή χρησιμοποίησε τη γραμμή αναζήτησης στην αρχική. Επίλεξε Βραχυχρόνια ή Μηνιαία, βάλε προορισμό (προαιρετικά ημερομηνίες/επισκέπτες) και πάτησε Αναζήτηση.",
    category: "search",
    audience: "visitor",
    relatedRoutes: [...R],
    priority: 100,
    quickSuggestion: true,
    suggestionContexts: ["home", "public_search"],
    suggestionLabel: "Πώς κάνω αναζήτηση;",
    keywords: ["αναζητηση", "search", "ψαχνω"],
    actionLinks: [{ label: "Άνοιγμα αναζήτησης", href: "/listings?rentalType=short_term" }],
  },
  {
    id: "search-dates-required",
    question: "Χρειάζεται να βάλω ημερομηνίες για να ψάξω;",
    answer:
      "Όχι. Μπορείς να κάνεις αναζήτηση χωρίς ημερομηνίες. Σε βραχυχρόνια αναζήτηση, αν δεν βάλεις ημερομηνίες, οι τιμές εμφανίζονται ενδεικτικά για 5 διανυκτερεύσεις.",
    category: "search",
    audience: "visitor",
    relatedRoutes: [...R],
    priority: 95,
    quickSuggestion: true,
    suggestionContexts: ["home", "public_search"],
    suggestionLabel: "Χρειάζεται να βάλω ημερομηνίες;",
    keywords: ["ημερομην", "υποχρεωτικ", "χωρις"],
  },
  {
    id: "search-no-location",
    question: "Μπορώ να κάνω αναζήτηση χωρίς προορισμό;",
    answer:
      "Ναι. Μπορείς να κάνεις αναζήτηση χωρίς πόλη — θα δεις αποτελέσματα σε ευρύτερη περιοχή ή σε όλη την Ελλάδα, ανάλογα με τα φίλτρα. Για πιο στοχευμένα αποτελέσματα, βάλε προορισμό ή χρησιμοποίησε τον χάρτη.",
    category: "search",
    audience: "visitor",
    relatedRoutes: [...R],
    priority: 70,
    quickSuggestion: false,
    suggestionContexts: ["public_search"],
  },
  {
    id: "search-no-guests",
    question: "Μπορώ να κάνω αναζήτηση χωρίς επισκέπτες;",
    answer: "Ναι. Οι επισκέπτες είναι προαιρετικοί. Η αναζήτηση λειτουργεί κανονικά χωρίς αριθμό επισκεπτών.",
    category: "search",
    audience: "visitor",
    relatedRoutes: [...R],
    priority: 90,
    quickSuggestion: true,
    suggestionContexts: ["public_search"],
    keywords: ["επισκεπτ", "guests", "ποιος"],
  },
  {
    id: "search-mode-switch",
    question: "Πώς αλλάζω από βραχυχρόνια σε μηνιαία μίσθωση;",
    answer:
      "Στη γραμμή αναζήτησης, πάτησε το tab Μηνιαία (ή Βραχυχρόνια). Η αλλαγή ενημερώνει τα πεδία — βραχυχρόνια χρησιμοποιεί ημερομηνίες, μηνιαία χρησιμοποιεί μήνα έναρξης και διάρκεια.",
    category: "search",
    audience: "visitor",
    relatedRoutes: [...R],
    priority: 75,
    quickSuggestion: false,
    suggestionContexts: ["public_search"],
  },
  {
    id: "search-short-term-meaning",
    question: "Τι σημαίνει βραχυχρόνια διαμονή;",
    answer:
      "Βραχυχρόνια διαμονή σημαίνει ενοικίαση για λίγες ημέρες ή εβδομάδες — με ημερομηνίες άφιξης και αναχώρησης. Στο Midora στέλνεις αίτημα διαθεσιμότητας στον ιδιοκτήτη.",
    category: "search",
    audience: "visitor",
    relatedRoutes: [...R],
    priority: 60,
    quickSuggestion: false,
    suggestionContexts: ["public_search", "home"],
  },
  {
    id: "search-monthly-meaning",
    question: "Τι σημαίνει μηνιαία / μεσοπρόθεσμη μίσθωση;",
    answer:
      "Μηνιαία ή μεσοπρόθεσμη μίσθωση είναι διαμονή για μήνες (π.χ. 1–12 μήνες). Στην αναζήτηση επιλέγεις μήνα έναρξης και διάρκεια. Στέλνεις αίτημα μίσθωσης στον ιδιοκτήτη.",
    category: "search",
    audience: "visitor",
    relatedRoutes: [...R],
    priority: 60,
    quickSuggestion: false,
    suggestionContexts: ["public_search"],
  },
  {
    id: "search-set-dates",
    question: "Πώς βάζω ημερομηνίες;",
    answer:
      "Στη γραμμή αναζήτησης (αρχική ή /listings), πάτησε το πεδίο ημερομηνιών, επίλεξε άφιξη και αναχώρηση και επιβεβαίωσε. Οι τιμές και τα αποτελέσματα ενημερώνονται για το διάστημα που διάλεξες.",
    category: "search",
    audience: "visitor",
    relatedRoutes: [...R],
    priority: 96,
    quickSuggestion: true,
    suggestionContexts: ["public_search"],
    keywords: ["ημερομην", "dates", "βαζω"],
    actionLinks: [{ label: "Άνοιγμα αναζήτησης", href: "/listings?rentalType=short_term" }],
  },
  {
    id: "search-pets",
    question: "Πώς βάζω κατοικίδια στην αναζήτηση;",
    answer:
      "Άνοιξε το πεδίο Επισκέπτες/Ποιος στη γραμμή αναζήτησης και αύξησε τον αριθμό Κατοικιδίων. Τότε εμφανίζονται αγγελίες που επιτρέπουν κατοικίδια.",
    category: "search",
    audience: "visitor",
    relatedRoutes: [...R],
    priority: 88,
    quickSuggestion: true,
    suggestionContexts: ["public_search"],
    keywords: ["κατοικιδ", "pets", "σκυλος", "γατα"],
  },
  {
    id: "search-filters",
    question: "Πώς λειτουργούν τα φίλτρα;",
    answer:
      "Πάτησε Φίλτρα στη σελίδα αναζήτησης για τιμή, δωμάτια, μπάνια, πάρκινγκ, παροχές κ.λπ. Τα φίλτρα εφαρμόζονται στα αποτελέσματα και στον χάρτη.",
    category: "search",
    audience: "visitor",
    relatedRoutes: ["/listings"],
    priority: 65,
    quickSuggestion: false,
    suggestionContexts: ["public_search"],
  },
  {
    id: "search-map",
    question: "Πώς χρησιμοποιώ τον χάρτη;",
    answer:
      "Στην αναζήτηση, άνοιξε τον χάρτη για να δεις αγγελίες στην περιοχή. Κάνε zoom, μετακίνησε την περιοχή και χρησιμοποίησε «Αναζήτηση σε αυτή την περιοχή» αν είναι διαθέσιμο.",
    category: "search",
    audience: "visitor",
    relatedRoutes: ["/listings"],
    priority: 85,
    quickSuggestion: true,
    suggestionContexts: ["public_search"],
    suggestionLabel: "Πώς λειτουργεί ο χάρτης;",
    keywords: ["χαρτης", "map", "zoom"],
  },
  {
    id: "search-5-nights-price",
    question: "Γιατί βλέπω τιμή για 5 διανυκτερεύσεις;",
    answer:
      "Σε βραχυχρόνια αναζήτηση χωρίς ημερομηνίες, το Midora δείχνει ενδεικτική τιμή για 5 διανυκτερεύσεις. Αν βάλεις ημερομηνίες, η τιμή υπολογίζεται για τις νύχτες που επέλεξες.",
    category: "search",
    audience: "visitor",
    relatedRoutes: [...R],
    priority: 82,
    quickSuggestion: true,
    suggestionContexts: ["public_search"],
  },
  {
    id: "search-unavailable-dates",
    question: "Γιατί κάποιες ημερομηνίες δεν είναι διαθέσιμες;",
    answer:
      "Οι μη διαθέσιμες ημερομηνίες είναι κλεισμένες από τον ιδιοκτήτη ή δεν πληρούν ελάχιστη διαμονή. Δοκίμασε άλλο range ή άλλη αγγελία.",
    category: "search",
    audience: "visitor",
    relatedRoutes: [...R],
    priority: 55,
    quickSuggestion: false,
    suggestionContexts: ["public_search", "public_listing"],
  },
  {
    id: "search-location-only",
    question: "Μπορώ να ψάξω μόνο με περιοχή;",
    answer: "Ναι. Βάλε μόνο προορισμό στη γραμμή αναζήτησης χωρίς ημερομηνίες ή επισκέπτες και πάτησε Αναζήτηση.",
    category: "search",
    audience: "visitor",
    relatedRoutes: [...R],
    priority: 50,
    quickSuggestion: false,
    suggestionContexts: ["public_search"],
  },
  {
    id: "search-dates-only",
    question: "Μπορώ να ψάξω μόνο με ημερομηνίες;",
    answer:
      "Μπορείς να βάλεις ημερομηνίες χωρίς προορισμό — θα δεις αποτελέσματα σε ευρύτερη περιοχή. Για καλύτερα αποτελέσματα, συνδύασε και προορισμό.",
    category: "search",
    audience: "visitor",
    relatedRoutes: [...R],
    priority: 45,
    quickSuggestion: false,
    suggestionContexts: ["public_search"],
  },
  {
    id: "search-total-price",
    question: 'Τι σημαίνει η τιμή "συνολικά";',
    answer:
      "Συνολικά σημαίνει ενδεικτικό σύνολο για το επιλεγμένο διάστημα (π.χ. 5 νύχτες ή οι ημερομηνίες που έβαλες). Δεν είναι τελική κράτηση — η τελική τιμή επιβεβαιώνεται από τον ιδιοκτήτη.",
    category: "search",
    audience: "visitor",
    relatedRoutes: [...R],
    priority: 72,
    quickSuggestion: true,
    suggestionContexts: ["public_search", "public_listing"],
    suggestionLabel: 'Τι σημαίνει η τιμή "συνολικά";',
  },
  {
    id: "home-what-is-midora",
    question: "Τι είναι το Midora;",
    answer:
      "Το Midora είναι πλατφόρμα αγγελιών για βραχυχρόνια και μηνιαία/μεσοπρόθεσμη μίσθωση στην Ελλάδα. Συνδέει επισκέπτες με ιδιοκτήτες μέσω αιτημάτων — δεν ολοκληρώνει κρατήσεις ή πληρωμές.",
    category: "search",
    audience: "all",
    relatedRoutes: ["/"],
    priority: 80,
    quickSuggestion: true,
    suggestionContexts: ["home"],
  },
];
