import type { FaqItem } from "@/lib/assistant/faq-types";

const R = ["/listings/", "/dashboard/listings/"] as const;

export const FAQ_PHOTOS_AMENITIES: FaqItem[] = [
  {
    id: "photos-amenities-view-all-photos",
    question: "Πώς βλέπω όλες τις φωτογραφίες;",
    answer:
      "Στην αγγελία, πάτησε σε φωτογραφία στην κορυφή για άνοιγμα gallery. Μπορείς να δεις όλες τις φωτογραφίες, συχνά ομαδοποιημένες ανά χώρο.",
    category: "photos_amenities",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 90,
    quickSuggestion: true,
    suggestionContexts: ["public_listing"],
    keywords: ["φωτογραφ", "gallery", "ολες"],
  },
  {
    id: "photos-amenities-room-sections",
    question: "Γιατί οι φωτογραφίες είναι χωρισμένες ανά χώρο;",
    answer:
      "Ο ιδιοκτήτης οργανώνει τις φωτογραφίες ανά δωμάτιο ή χώρο (π.χ. κουζίνα, υπνοδωμάτιο) ώστε να κατανοείς καλύτερα το ακίνητο πριν στείλεις αίτημα.",
    category: "photos_amenities",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 70,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["χωρο", "room", "δωματι"],
  },
  {
    id: "photos-amenities-room-photos",
    question: "Τι είναι οι φωτογραφίες ανά δωμάτιο;",
    answer:
      "Είναι φωτογραφίες που ο ιδιοκτήτης ανέβασε και έβαλε σε κατηγορία δωματίου/χώρου. Βοηθούν να δεις κάθε μέρος του ακινήτου ξεχωριστά.",
    category: "photos_amenities",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 65,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["δωματι", "room photos"],
  },
  {
    id: "photos-amenities-where",
    question: "Πού βλέπω τις παροχές;",
    answer:
      "Στην αγγελία, ενότητα «Παροχές» ή «Τι προσφέρει ο χώρος» — εκεί εμφανίζονται όλες οι παροχές που έχει επιλέξει ο ιδιοκτήτης.",
    category: "photos_amenities",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 88,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["παροχ", "amenities"],
  },
  {
    id: "photos-amenities-what-offers",
    question: "Τι σημαίνει «Τι προσφέρει ο χώρος»;",
    answer:
      "Είναι η λίστα παροχών του ακινήτου — Wi-Fi, κλιματισμός, κουζίνα, parking κ.λπ. — όπως τις έχει δηλώσει ο ιδιοκτήτης. Δεν εγγυάται το Midora ότι όλες ισχύουν — επιβεβαίωσε στο αίτημα αν χρειάζεται.",
    category: "photos_amenities",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 75,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["προσφερ", "χωρος", "offers"],
  },
  {
    id: "photos-amenities-wifi",
    question: "Πώς βλέπω αν έχει Wi-Fi;",
    answer:
      "Δες την ενότητα «Παροχές». Αν ο ιδιοκτήτης έχει επιλέξει Wi-Fi, εμφανίζεται εκεί. Μπορείς επίσης να το ρωτήσεις στο αίτημα.",
    category: "photos_amenities",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 80,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["wifi", "internet"],
  },
  {
    id: "photos-amenities-kitchen",
    question: "Πώς βλέπω αν έχει κουζίνα;",
    answer:
      "Στις «Παροχές» αναζήτησε «Κουζίνα» ή σχετικές επιλογές (πλήρης/μικρή κουζίνα). Οι φωτογραφίες κουζίνας βοηθούν επίσης στην ενότητα gallery.",
    category: "photos_amenities",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 78,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["κουζινα", "kitchen"],
  },
  {
    id: "photos-amenities-washer",
    question: "Πώς βλέπω αν έχει πλυντήριο;",
    answer:
      "Δες «Παροχές» για πλυντήριο ρούχων ή πλυντήριο/στεγνωτήριο. Αν δεν αναφέρεται, ρώτα τον ιδιοκτήτη στο αίτημα.",
    category: "photos_amenities",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 72,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["πλυντηρι", "washer", "laundry"],
  },
  {
    id: "photos-amenities-ac",
    question: "Πώς βλέπω αν έχει κλιματισμό;",
    answer:
      "Στις «Παροχές» εμφανίζεται «Κλιματισμός» αν ο ιδιοκτήτης το έχει επιλέξει. Σε καλοκαίρι, ρώτα και για δωμάτια με A/C στο αίτημα.",
    category: "photos_amenities",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 76,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["κλιματισμ", "ac", "aircon"],
  },
  {
    id: "photos-amenities-workspace",
    question: "Πώς βλέπω αν έχει χώρο εργασίας;",
    answer:
      "Δες τις παροχές και τις φωτογραφίες γραφείου/καθιστικού. Αν δεν αναφέρεται ρητά workspace, ρώτα στο αίτημα.",
    category: "photos_amenities",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 60,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["εργασια", "workspace", "desk"],
  },
  {
    id: "photos-amenities-parking",
    question: "Πώς βλέπω αν έχει parking;",
    answer:
      "Στις «Παροχές» αναζήτησε parking/θέση στάθμευσης. Μπορείς επίσης να φιλτράρεις αγγελίες με parking στην αναζήτηση (/listings).",
    category: "photos_amenities",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 74,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["parking", "παρκιν"],
  },
  {
    id: "photos-amenities-pets",
    question: "Πώς βλέπω αν επιτρέπονται κατοικίδια;",
    answer:
      "Δες «Παροχές» και «Κανόνες» στην αγγελία. Αν επιτρέπονται κατοικίδια, συνήθως αναφέρεται ρητά. Αλλιώς ρώτα στο αίτημα πριν ταξιδέψεις.",
    category: "photos_amenities",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 82,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["κατοικιδ", "pets"],
  },
];
