import type { FaqItem } from "@/lib/assistant/faq-types";

export const FAQ_SAFETY: FaqItem[] = [
  {
    id: "safety-communicate-in-midora",
    question: "Είναι ασφαλές να επικοινωνώ μέσα από το Midora;",
    answer:
      "Για την ασφάλειά σου, επικοινώνησε μέσα από το Midora και επιβεβαίωσε τα στοιχεία του ακινήτου πριν προχωρήσεις σε οποιαδήποτε πληρωμή ή συμφωνία. Το Midora δεν διαχειρίζεται πληρωμές, κρατήσεις ή προκαταβολές. Η τελική συμφωνία γίνεται απευθείας με τον ιδιοκτήτη.",
    category: "safety",
    audience: "all",
    relatedRoutes: ["/listings/", "/dashboard/"],
    priority: 95,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["ασφαλ", "safe", "επικοινων"],
  },
  {
    id: "safety-send-deposit",
    question: "Πρέπει να στείλω προκαταβολή στον ιδιοκτήτη;",
    answer:
      "Το Midora δεν διαχειρίζεται πληρωμές, κρατήσεις ή προκαταβολές. Πριν στείλεις οποιοδήποτε ποσό απευθείας σε ιδιοκτήτη, επιβεβαίωσε την ταυτότητά του, τη διαθεσιμότητα, τα στοιχεία του ακινήτου και τους όρους της συμφωνίας. Για μηνιαία ή μακροχρόνια μίσθωση, είναι ασφαλέστερο να δεις πρώτα το ακίνητο ή να επιβεβαιώσεις με σιγουριά τα στοιχεία της συμφωνίας.",
    category: "safety",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 102,
    quickSuggestion: true,
    suggestionContexts: ["public_listing"],
    keywords: ["προκαταβολ", "deposit", "πληρωμ"],
  },
  {
    id: "safety-midora-protect-payment",
    question: "Το Midora κρατά ή προστατεύει την πληρωμή μου;",
    answer:
      "Όχι. Το Midora λειτουργεί ως πλατφόρμα προβολής αγγελιών και αρχικής επικοινωνίας. Δεν κρατά χρήματα, δεν επεξεργάζεται πληρωμές και δεν παρέχει προστασία πληρωμών ή προκαταβολών.",
    category: "safety",
    audience: "all",
    relatedRoutes: ["/listings/", "/terms", "/help"],
    priority: 101,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["προστατευ", "κρατα", "πληρωμ", "payment"],
  },
  {
    id: "safety-message-owner",
    question: "Μπορώ να στείλω μήνυμα στον ιδιοκτήτη μέσα από το Midora;",
    answer:
      "Ναι. Από τη δημόσια αγγελία μπορείς να στείλεις μήνυμα στον ιδιοκτήτη ή οικοδεσπότη για διαθεσιμότητα, όρους και λεπτομέρειες του ακινήτου. Η επικοινωνία μέσα από το Midora βοηθά να κρατάς οργανωμένο ιστορικό, αλλά η τελική συμφωνία γίνεται απευθείας μεταξύ των μερών.",
    category: "safety",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 99,
    quickSuggestion: true,
    suggestionContexts: ["public_listing"],
    keywords: ["μηνυμα", "message", "οικοδεσποτ", "ιδιοκτητ"],
  },
  {
    id: "safety-midora-payments",
    question: "Το Midora διαχειρίζεται πληρωμές;",
    answer:
      "Όχι. Το Midora δεν επεξεργάζεται πληρωμές, κρατήσεις ή refunds. Στέλνεις αίτημα ή μήνυμα, επικοινωνείς με τον ιδιοκτήτη και συμφωνείτε απευθείας — εκτός πλατφόρμας για πληρωμή.",
    category: "safety",
    audience: "all",
    relatedRoutes: ["/listings/", "/dashboard/"],
    priority: 100,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["πληρωμ", "payment", "refund"],
  },
  {
    id: "safety-pay-before-talk",
    question: "Πρέπει να στείλω χρήματα πριν μιλήσω με τον ιδιοκτήτη;",
    answer:
      "Όχι. Μην στέλνεις χρήματα ή προκαταβολή πριν επιβεβαιώσεις διαθεσιμότητα, ταυτότητα ιδιοκτήτη και όρους. Το Midora δεν εγγυάται πληρωμές. Για την ασφάλειά σου, επικοινώνησε μέσα από το Midora πρώτα.",
    category: "safety",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 98,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["χρηματα", "money", "προκαταβολ"],
  },
  {
    id: "safety-suspicious-listing",
    question: "Τι κάνω αν μια αγγελία φαίνεται ύποπτη;",
    answer:
      "Μην στείλεις χρήματα εκτός Midora. Στείλε αίτημα ή μήνυμα μέσα από την πλατφόρμα, έλεγξε προφίλ ιδιοκτήτη και εξωτερικούς συνδέσμους. Αν κάτι δεν σου φαίνεται σωστό, χρησιμοποίησε «Αναφορά αγγελίας» ή «Αναφορά συνομιλίας» ή επικοινώνησε με υποστήριξη.",
    category: "safety",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 88,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["υποπτο", "suspicious", "scam"],
  },
  {
    id: "safety-report-listing",
    question: "Πώς κάνω αναφορά αγγελίας;",
    answer:
      "Στην δημόσια αγγελία πάτα «Αναφορά αγγελίας» και επίλεξε λόγο (π.χ. ύποπτη αγγελία, λάθος πληροφορίες, λάθος τοποθεσία). Η αναφορά είναι για εσωτερικό έλεγχο/moderation — δεν σημαίνει διαχείριση διαφορών ή αποζημίωσης από το Midora.",
    category: "safety",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 75,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["αναφορα", "report"],
  },
  {
    id: "safety-no-exact-address",
    question: "Γιατί δεν εμφανίζεται ακριβής διεύθυνση;",
    answer:
      "Η τοποθεσία εμφανίζεται κατά προσέγγιση για λόγους ιδιωτικότητας. Η ακριβής διεύθυνση κοινοποιείται από τον ιδιοκτήτη μετά την επικοινωνία, εκτός αν ο ιδιοκτήτης έχει επιλέξει δημόσια ακριβή εμφάνιση.",
    category: "safety",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 70,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["διευθυνση", "address", "ακριβ"],
  },
  {
    id: "safety-real-listing",
    question: "Πώς ξέρω ότι μια αγγελία είναι πραγματική;",
    answer:
      "Έλεγξε: πλήρες προφίλ ιδιοκτήτη, πολλές φωτογραφίες, ξεκάθαρη περιγραφή, εξωτερικό link (προαιρετικό), απάντηση σε αίτημα. Μην πληρώνεις πριν επιβεβαιώσεις διαθεσιμότητα. Εξωτερικοί σύνδεσμοι δεν σημαίνουν επαλήθευση από το Midora.",
    category: "safety",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 82,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["πραγματικ", "real", "εμπιστοσυνη"],
  },
  {
    id: "safety-external-link-trust",
    question: "Τι σημαίνει εξωτερικός σύνδεσμος ως trust signal;",
    answer:
      "Αν ο ιδιοκτήτης έχει δημόσιο link σε Airbnb/Booking κ.λπ., δείχνει ότι η αγγελία υπάρχει και αλλού. Δεν αποτελεί επαλήθευση ή έγκριση από το Midora και δεν εγγυάται διαθεσιμότητα ή ασφάλεια.",
    category: "safety",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 65,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["trust", "εξωτερικ", "link"],
  },
  {
    id: "safety-last-updated",
    question: "Τι σημαίνει «τελευταία ενημέρωση αγγελίας»;",
    answer:
      "Δείχνει πότε ενημερώθηκε τελευταία η αγγελία από τον ιδιοκτήτη (π.χ. τιμές, φωτογραφίες). Πιο πρόσφατη ενημέρωση συνήθως σημαίνει πιο ενεργή διαχείριση.",
    category: "safety",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 58,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["ενημερωση", "updated", "τελευταια"],
  },
  {
    id: "safety-complete-owner-profile",
    question: "Τι σημαίνει συμπληρωμένο προφίλ ιδιοκτήτη;",
    answer:
      "Ιδιοκτήτης με όνομα, φωτογραφία, βιογραφία και γλώσσες — όχι κενό προφίλ. Βοηθά να ξέρεις με ποιον επικοινωνείς. Δεν εγγυάται από μόνο του ασφάλεια, αλλά είναι θετικό σήμα.",
    category: "safety",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 62,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["προφιλ", "profile", "συμπληρωμεν"],
  },
];
