import type { FaqItem } from "@/lib/assistant/faq-types";

const R = ["/listings/", "/dashboard/listings/"] as const;

export const FAQ_PRICING_AVAILABILITY: FaqItem[] = [
  {
    id: "pricing-how-calculated",
    question: "Πώς υπολογίζεται η τιμή;",
    answer:
      "Ο ιδιοκτήτης ορίζει τιμές (ανά νύχτα ή ανά μήνα). Σε βραχυχρόνια, το Midora υπολογίζει ενδεικτικό σύνολο με βάση το ημερολόγιο τιμών — Σαββατοκύριακο, ειδικές περίοδοι, εκπτώσεις 7+/28+ νυχτών. Η τελική τιμή επιβεβαιώνεται από τον ιδιοκτήτη.",
    category: "pricing_availability",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 95,
    quickSuggestion: true,
    suggestionContexts: ["public_listing"],
    keywords: ["τιμη", "price", "υπολογ"],
  },
  {
    id: "pricing-changes-with-dates",
    question: "Γιατί η τιμή αλλάζει όταν βάζω ημερομηνίες;",
    answer:
      "Κάθε ημέρα μπορεί να έχει διαφορετική τιμή (π.χ. Σαββατοκύριακο, ειδική περίοδος). Όταν επιλέγεις ημερομηνίες, το σύνολο υπολογίζεται για τις συγκεκριμένες νύχτες — όχι για το ενδεικτικό 5-νύχτες preview.",
    category: "pricing_availability",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 90,
    quickSuggestion: true,
    suggestionContexts: ["public_listing"],
    keywords: ["αλλαζ", "ημερομην", "τιμη"],
  },
  {
    id: "pricing-5-nights-display",
    question: "Γιατί εμφανίζεται τιμή για 5 διανυκτερεύσεις;",
    answer:
      "Χωρίς επιλεγμένες ημερομηνίες, το Midora δείχνει ενδεικτική τιμή για 5 διανυκτερεύσεις ώστε να συγκρίνεις αγγελίες. Με ημερομηνίες, η τιμή αλλάζει για το δικό σου διάστημα.",
    category: "pricing_availability",
    audience: "visitor",
    relatedRoutes: ["/listings/", "/listings"],
    priority: 88,
    quickSuggestion: true,
    suggestionContexts: ["public_listing", "public_search"],
    keywords: ["5", "διανυκτερευ", "ενδεικτικ"],
  },
  {
    id: "pricing-final-price",
    question: "Είναι τελική η τιμή που βλέπω;",
    answer:
      "Όχι — είναι ενδεικτική. Η τελική τιμή και όροι επιβεβαιώνονται από τον ιδιοκτήτη μετά το αίτημα. Το Midora δεν ολοκληρώνει πληρωμές ή κρατήσεις.",
    category: "pricing_availability",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 92,
    quickSuggestion: true,
    suggestionContexts: ["public_listing"],
    keywords: ["τελικ", "final", "ενδεικτικ"],
  },
  {
    id: "pricing-midora-commission",
    question: "Το Midora χρεώνει προμήθεια;",
    answer:
      "Το Midora είναι πλατφόρμα αγγελιών και αιτημάτων — δεν επεξεργάζεται πληρωμές και δεν χρεώνει προμήθεια κράτησης. Οποιαδήποτε συμφωνία τιμής γίνεται απευθείας με τον ιδιοκτήτη.",
    category: "pricing_availability",
    audience: "all",
    relatedRoutes: [...R],
    priority: 85,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["προμηθει", "commission", "χρεω"],
  },
  {
    id: "pricing-pay-through-midora",
    question: "Μπορώ να πληρώσω μέσα από το Midora;",
    answer:
      "Όχι. Το Midora δεν επεξεργάζεται πληρωμές. Στέλνεις αίτημα, επικοινωνείς με τον ιδιοκτήτη και συμφωνείτε απευθείας για τρόπο και χρόνο πληρωμής.",
    category: "pricing_availability",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 100,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["πληρωμ", "payment", "checkout"],
  },
  {
    id: "pricing-owner-confirms",
    question: "Τι σημαίνει «η τελική συμφωνία επιβεβαιώνεται από τον ιδιοκτήτη»;",
    answer:
      "Το Midora δείχνει ενδεικτικές τιμές και σου επιτρέπει να στείλεις αίτημα. Ο ιδιοκτήτης ελέγχει διαθεσιμότητα, τιμή, κανόνες και απαντά. Η οριστική συμφωνία γίνεται εκτός Midora, απευθείας μαζί του.",
    category: "pricing_availability",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 80,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["συμφων", "επιβεβαιω"],
  },
  {
    id: "availability-see-dates",
    question: "Πώς βλέπω διαθέσιμες ημερομηνίες;",
    answer:
      "Στην αγγελία, στην ενότητα «Διαθεσιμότητα» ή «Ενδεικτική διαθεσιμότητα», δες το ημερολόγιο. Οι διαθέσιμες ημέρες επιλέγονται — οι κλειστές εμφανίζονται γκρι.",
    category: "pricing_availability",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    relatedFeature: "calendar",
    priority: 87,
    quickSuggestion: true,
    suggestionContexts: ["public_listing"],
    keywords: ["διαθεσιμ", "availability", "ημερολογ"],
  },
  {
    id: "availability-grey-dates",
    question: "Τι σημαίνουν οι γκρι ημερομηνίες στο ημερολόγιο;",
    answer:
      "Οι γκρι ημερομηνίες είναι μη διαθέσιμες — κλεισμένες από τον ιδιοκτήτη ή στο παρελθόν. Δεν μπορείς να τις επιλέξεις για αίτημα.",
    category: "pricing_availability",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 82,
    quickSuggestion: true,
    suggestionContexts: ["public_listing"],
    keywords: ["γκρι", "grey", "κλεισ"],
  },
  {
    id: "availability-dash-meaning",
    question: "Τι σημαίνει η παύλα πάνω σε ημερομηνία;",
    answer:
      "Η παύλα (–) δείχνει ότι η ημέρα είναι μπλοκαρισμένη/μη διαθέσιμη. Δοκίμασε άλλες ημερομηνίες ή στείλε αίτημα με εναλλακτικό range.",
    category: "pricing_availability",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 75,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["παυλα", "dash", "blocked"],
  },
  {
    id: "availability-select-blocked",
    question: "Μπορώ να επιλέξω ημερομηνίες που είναι κλειστές;",
    answer:
      "Όχι — οι κλειστές ημερομηνίες δεν επιλέγονται. Αν χρειάζεσαι εκείνες τις ημέρες, στείλε αίτημα με εναλλακτικές ημερομηνίες ή ρώτα τον ιδιοκτήτη.",
    category: "pricing_availability",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 70,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["κλειστ", "blocked", "επιλογ"],
  },
  {
    id: "availability-range-not-selectable",
    question: "Γιατί δεν μπορώ να επιλέξω κάποιο range ημερομηνιών;",
    answer:
      "Μπορεί να υπάρχει κλειστή ημέρα μέσα στο range, ελάχιστη διαμονή που δεν πληρούται, ή conflict με τις ρυθμίσεις του ιδιοκτήτη. Δοκίμασε μικρότερο ή άλλο διάστημα.",
    category: "pricing_availability",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 65,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["range", "διαστημα", "επιλογ"],
  },
  {
    id: "availability-change-dates-in-listing",
    question: "Τι γίνεται αν αλλάξω ημερομηνίες μέσα στην αγγελία;",
    answer:
      "Η ενδεικτική τιμή και το ημερολόγιο ενημερώνονται για το νέο range. Το αίτημα που θα στείλεις θα περιλαμβάνει τις ημερομηνίες που έχεις επιλέξει εκείνη τη στιγμή.",
    category: "pricing_availability",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 60,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["αλλαγ", "ημερομην", "range"],
  },
  {
    id: "owner-availability-block-dates",
    question: "Πώς κλείνω ημερομηνίες;",
    answer:
      "1. Άνοιξε την αγγελία → καρτέλα Διαθεσιμότητα.\n2. Κλικ σε ημερομηνία ή range για block (κλείσιμο).\n3. Αποθήκευσε. Οι κλειστές ημερομηνίες δεν δέχονται αιτήματα.",
    category: "pricing_availability",
    audience: "owner",
    relatedRoutes: ["/dashboard/listings/"],
    priority: 96,
    quickSuggestion: true,
    suggestionContexts: ["owner_availability"],
    keywords: ["κλειν", "block", "κλειστο"],
    actionLinks: [{ label: "Διαθεσιμότητα", href: "/dashboard/listings/{id}/availability" }],
  },
  {
    id: "owner-availability-daily-price",
    question: "Πώς αλλάζω τιμή ημέρας;",
    answer:
      "Στην καρτέλα Διαθεσιμότητα, επίλεξε ημερομηνία και όρισε τιμή ανά νύχτα. Μπορείς να ορίσεις διαφορετική τιμή ανά ημέρα στο ημερολόγιο.",
    category: "pricing_availability",
    audience: "owner",
    relatedRoutes: ["/dashboard/listings/"],
    priority: 94,
    quickSuggestion: true,
    suggestionContexts: ["owner_availability"],
    keywords: ["τιμη", "ημερα", "νυχτα", "daily"],
    actionLinks: [{ label: "Διαθεσιμότητα", href: "/dashboard/listings/{id}/availability" }],
  },
  {
    id: "owner-availability-weekend-price",
    question: "Πώς βάζω τιμή Σαββατοκύριακου;",
    answer:
      "Στην καρτέλα Διαθεσιμότητα, όρισε τιμή Σαββατοκύριακου (ή ανά ημέρα για Σάβ/Κυρ) στο αντίστοιχο πεδίο. Αποθήκευσε για να εφαρμοστεί στις σχετικές ημερομηνίες.",
    category: "pricing_availability",
    audience: "owner",
    relatedRoutes: ["/dashboard/listings/"],
    priority: 92,
    quickSuggestion: true,
    suggestionContexts: ["owner_availability"],
    keywords: ["σαββατοκυριακ", "weekend"],
    actionLinks: [{ label: "Διαθεσιμότητα", href: "/dashboard/listings/{id}/availability" }],
  },
];
