import type { FaqItem } from "@/lib/assistant/faq-types";

const R = ["/dashboard/listings/", "/listings/"] as const;

export const FAQ_COHOSTS: FaqItem[] = [
  {
    id: "cohosts-what-is",
    question: "Τι είναι ο συνοικοδεσπότης;",
    answer:
      "Ο συνοικοδεσπότης (co-host) είναι άτομο που βοηθά τον ιδιοκτήτη να διαχειρίζεται μια αγγελία — π.χ. απαντά σε αιτήματα ή ενημερώνει διαθεσιμότητα — με δικαιώματα που ορίζει ο ιδιοκτήτης.",
    category: "cohosts",
    audience: "all",
    relatedRoutes: [...R],
    priority: 90,
    quickSuggestion: false,
    suggestionContexts: ["owner_listing_workspace", "public_listing"],
    keywords: ["συνοικοδεσποτ", "cohost", "τι ειναι"],
  },
  {
    id: "cohosts-add",
    question: "Πώς προσθέτω συνοικοδεσπότη;",
    answer:
      "1. Άνοιξε την αγγελία από /dashboard/listings.\n2. Καρτέλα Συνοικοδεσπότες.\n3. Πρόσκληση συνοικοδεσπότη → email + επίπεδο δικαιωμάτων.\n4. Ο προσκεκλημένος αποδέχεται την πρόσκληση.",
    category: "cohosts",
    audience: "owner",
    relatedRoutes: ["/dashboard/listings/"],
    priority: 95,
    quickSuggestion: true,
    suggestionContexts: ["owner_dashboard", "owner_listing_workspace"],
    keywords: ["προσθεσ", "add", "προσκληση"],
    actionLinks: [{ label: "Συνοικοδεσπότες", href: "/dashboard/listings/{id}/cohosts" }],
  },
  {
    id: "cohosts-permissions",
    question: "Τι δικαιώματα έχει ο συνοικοδεσπότης;",
    answer:
      "Ο ιδιοκτήτης επιλέγει επίπεδο: πλήρης διαχείριση, μηνύματα+διαθεσιμότητα, ή μόνο μηνύματα. Ο συνοικοδεσπότης βλέπει μόνο ό,τι του επιτρέπεται — δεν αντικαθιστά τον ιδιοκτήτη.",
    category: "cohosts",
    audience: "all",
    relatedRoutes: ["/dashboard/listings/"],
    priority: 88,
    quickSuggestion: false,
    suggestionContexts: ["owner_listing_workspace"],
    keywords: ["δικαιωματα", "permissions", "επιπεδο"],
  },
  {
    id: "cohosts-reply-messages",
    question: "Μπορεί ο συνοικοδεσπότης να απαντά σε μηνύματα;",
    answer:
      "Ναι, αν ο ιδιοκτήτης του έχει δώσει δικαίωμα μηνυμάτων (manage messages). Οι απαντήσεις εμφανίζονται στο thread του αιτήματος.",
    category: "cohosts",
    audience: "all",
    relatedRoutes: ["/dashboard/listings/"],
    priority: 85,
    quickSuggestion: true,
    suggestionContexts: ["owner_messages"],
    keywords: ["απαντ", "μηνυμα", "messages"],
    actionLinks: [{ label: "Αιτήματα", href: "/dashboard/listings/{id}/inquiries" }],
  },
  {
    id: "cohosts-change-availability",
    question: "Μπορεί ο συνοικοδεσπότης να αλλάζει διαθεσιμότητα;",
    answer:
      "Ναι, αν έχει δικαίωμα διαθεσιμότητας (π.χ. επίπεδο «Μηνύματα + διαθεσιμότητα» ή πλήρης διαχείριση). Αλλιώς βλέπει μόνο μηνύματα.",
    category: "cohosts",
    audience: "all",
    relatedRoutes: ["/dashboard/listings/"],
    priority: 82,
    quickSuggestion: false,
    suggestionContexts: ["owner_availability"],
    keywords: ["διαθεσιμοτητα", "availability"],
    actionLinks: [{ label: "Διαθεσιμότητα", href: "/dashboard/listings/{id}/availability" }],
  },
  {
    id: "cohosts-change-prices",
    question: "Μπορεί ο συνοικοδεσπότης να αλλάζει τιμές;",
    answer:
      "Μόνο αν έχει πλήρη διαχείριση ή ρητά δικαίωμα τιμών/διαθεσιμότητας. Στα άλλα επίπεδα δεν μπορεί να αλλάξει τιμές.",
    category: "cohosts",
    audience: "all",
    relatedRoutes: ["/dashboard/listings/"],
    priority: 78,
    quickSuggestion: false,
    suggestionContexts: ["owner_availability"],
    keywords: ["τιμη", "price", "pricing"],
  },
  {
    id: "cohosts-add-phone",
    question: "Μπορεί ο συνοικοδεσπότης να προσθέσει τηλέφωνο;",
    answer:
      "Αν έχει δικαίωμα επεξεργασίας αγγελίας/επικοινωνίας, μπορεί να βοηθήσει με στοιχεία επικοινωνίας της αγγελίας — σύμφωνα με τα δικαιώματα που ορίζει ο ιδιοκτήτης.",
    category: "cohosts",
    audience: "owner",
    relatedRoutes: ["/dashboard/listings/"],
    priority: 65,
    quickSuggestion: false,
    suggestionContexts: ["owner_listing_workspace"],
    keywords: ["τηλεφων", "phone", "contact"],
  },
  {
    id: "cohosts-remove",
    question: "Πώς αφαιρώ συνοικοδεσπότη;",
    answer:
      "1. Άνοιξε την αγγελία → Συνοικοδεσπότες.\n2. Βρες τον συνοικοδεσπότη.\n3. Αφαίρεση/Ακύρωση πρόσβασης.\n\nΜόνο ο ιδιοκτήτης μπορεί να αφαιρέσει συνοικοδεσπότη.",
    category: "cohosts",
    audience: "owner",
    relatedRoutes: ["/dashboard/listings/"],
    priority: 80,
    quickSuggestion: false,
    suggestionContexts: ["owner_listing_workspace"],
    keywords: ["αφαιρεσ", "remove", "διαγραφ"],
    actionLinks: [{ label: "Συνοικοδεσπότες", href: "/dashboard/listings/{id}/cohosts" }],
  },
  {
    id: "cohosts-delete-listing",
    question: "Μπορεί ο συνοικοδεσπότης να διαγράψει την αγγελία;",
    answer:
      "Όχι. Ο συνοικοδεσπότης δεν μπορεί να διαγράψει την αγγελία, να αφαιρέσει τον ιδιοκτήτη ή να διαχειριστεί billing/δημοσίευση, εκτός αν ο ιδιοκτήτης του έχει δώσει ρητά τέτοια δικαιώματα (συνήθως όχι).",
    category: "cohosts",
    audience: "all",
    relatedRoutes: ["/dashboard/listings/"],
    priority: 92,
    quickSuggestion: false,
    suggestionContexts: ["owner_listing_workspace"],
    keywords: ["διαγραφ", "delete", "listing"],
  },
  {
    id: "cohosts-public-display",
    question: "Πού εμφανίζεται ο συνοικοδεσπότης στη δημόσια αγγελία;",
    answer:
      "Αν ο ιδιοκτήτης το επιτρέπει, ο συνοικοδεσπότης μπορεί να εμφανίζεται στην ενότητα ιδιοκτήτη/οικοδεσπότη. Ο κύριος ιδιοκτήτης παραμένει υπεύθυνος για την αγγελία.",
    category: "cohosts",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 60,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["εμφανιζ", "public", "δημοσια"],
  },
  {
    id: "cohosts-public-profile",
    question: "Μπορεί ο επισκέπτης να δει το προφίλ του συνοικοδεσπότη;",
    answer:
      "Μόνο αν εμφανίζεται δημόσια στην αγγελία και έχει δημόσιο προφίλ. Συνήθως η κύρια επικοινωνία γίνεται με τον ιδιοκτήτη ή όποιον απαντά στο αίτημα.",
    category: "cohosts",
    audience: "visitor",
    relatedRoutes: ["/listings/"],
    priority: 55,
    quickSuggestion: false,
    suggestionContexts: ["public_listing"],
    keywords: ["προφιλ", "profile", "visitor"],
  },
];
