import type { FaqItem } from "@/lib/assistant/faq-types";

const R = ["/dashboard/listings"] as const;
const RW = ["/dashboard/listings/"] as const;

export const FAQ_OWNER_LISTING: FaqItem[] = [
  {
    id: "owner-listing-create",
    question: "Πώς ανεβάζω αγγελία;",
    answer:
      "1. Πήγαινε στο Dashboard → Τα ακίνητά μου (/dashboard/listings).\n2. Πάτησε Νέα αγγελία.\n3. Επίλεξε βραχυχρόνια ή μηνιαία.\n4. Συμπλήρωσε στοιχεία, φωτογραφίες, τιμές και διαθεσιμότητα.\n5. Δημοσίευσε από την καρτέλα Δημοσίευση.",
    category: "owner_listing",
    audience: "owner",
    relatedRoutes: [...R, "/dashboard/listings/new"],
    priority: 100,
    quickSuggestion: true,
    suggestionContexts: ["owner_dashboard", "owner_listing_workspace"],
    keywords: ["ανεβασ", "νεα", "create", "listing"],
    actionLinks: [
      { label: "Αγγελίες μου", href: "/dashboard/listings" },
      { label: "Νέα αγγελία", href: "/dashboard/listings/new" },
    ],
  },
  {
    id: "owner-listing-required-fields",
    question: "Τι στοιχεία χρειάζονται για μια αγγελία;",
    answer:
      "Βασικά: τίτλος, περιγραφή, τοποθεσία, τύπος μίσθωσης, χωρητικότητα, φωτογραφίες, τιμή και διαθεσιμότητα. Για δημοσίευση, έλεγξε την καρτέλα Δημοσίευση για τις προϋποθέσεις πληρότητας.",
    category: "owner_listing",
    audience: "owner",
    relatedRoutes: [...RW],
    priority: 90,
    quickSuggestion: false,
    suggestionContexts: ["owner_listing_workspace"],
    keywords: ["στοιχεια", "required", "υποχρεωτικ"],
  },
  {
    id: "owner-listing-short-term",
    question: "Μπορώ να ανεβάσω βραχυχρόνια αγγελία;",
    answer:
      "Ναι. Κατά τη δημιουργία ή επεξεργασία, επίλεξε βραχυχρόνια μίσθωση. Θα ορίσεις τιμές ανά νύχτα, ημερολόγιο διαθεσιμότητας και ελάχιστη διαμονή.",
    category: "owner_listing",
    audience: "owner",
    relatedRoutes: [...RW],
    priority: 85,
    quickSuggestion: false,
    suggestionContexts: ["owner_listing_workspace"],
    keywords: ["βραχυχρον", "short term"],
  },
  {
    id: "owner-listing-monthly",
    question: "Μπορώ να ανεβάσω μηνιαία αγγελία;",
    answer:
      "Ναι. Επίλεξε μηνιαία/μεσοπρόθεσμη μίσθωση και όρισε τιμή ανά μήνα, διάρκεια και βασικά στοιχεία. Οι επισκέπτες στέλνουν αίτημα μίσθωσης.",
    category: "owner_listing",
    audience: "owner",
    relatedRoutes: [...RW],
    priority: 85,
    quickSuggestion: false,
    suggestionContexts: ["owner_listing_workspace"],
    keywords: ["μηνιαι", "monthly"],
  },
  {
    id: "owner-listing-good-description",
    question: "Πώς γράφω καλή περιγραφή;",
    answer:
      "Γράψε ξεκάθαρα: τι είναι το ακίνητο, πού βρίσκεται (χωρίς ακριβή διεύθυνση), τι περιλαμβάνει, κανόνες, check-in/out. Χρησιμοποίησε ειλικρινείς πληροφορίες — βοηθάει στα αιτήματα.",
    category: "owner_listing",
    audience: "owner",
    relatedRoutes: [...RW],
    priority: 70,
    quickSuggestion: false,
    suggestionContexts: ["owner_listing_workspace"],
    keywords: ["περιγραφ", "description"],
    actionLinks: [{ label: "Επεξεργασία αγγελίας", href: "/dashboard/listings/{id}/edit" }],
  },
  {
    id: "owner-listing-how-many-photos",
    question: "Πόσες φωτογραφίες πρέπει να ανεβάσω;",
    answer:
      "Πρόσθεσε αρκετές φωτογραφίες για κάθε κύριο χώρο — συνήθως 5–15+ για καλή εικόνα. Η καρτέλα Δημοσίευση δείχνει αν πληροίς την ελάχιστη απαίτηση φωτογραφιών.",
    category: "owner_listing",
    audience: "owner",
    relatedRoutes: [...RW],
    priority: 88,
    quickSuggestion: true,
    suggestionContexts: ["owner_dashboard", "owner_listing_workspace", "owner_photos"],
    keywords: ["φωτογραφ", "ποσες", "photos"],
    actionLinks: [{ label: "Φωτογραφίες", href: "/dashboard/listings/{id}/photos" }],
  },
  {
    id: "owner-listing-upload-photos",
    question: "Πώς ανεβάζω φωτογραφίες;",
    answer:
      "1. Άνοιξε την αγγελία → καρτέλα Φωτογραφίες.\n2. Πάτησε «Προσθήκη φωτογραφιών» ή σύρε αρχεία.\n3. Περίμενε να ολοκληρωθεί το ανέβασμα.\n4. Ορίσε εξώφυλλο και σειρά όπως θέλεις.",
    category: "owner_listing",
    audience: "owner",
    relatedRoutes: [...RW],
    priority: 97,
    quickSuggestion: true,
    suggestionContexts: ["owner_dashboard", "owner_listing_workspace", "owner_photos"],
    keywords: ["ανεβασ", "upload", "φωτογραφ"],
    actionLinks: [{ label: "Φωτογραφίες", href: "/dashboard/listings/{id}/photos" }],
  },
  {
    id: "owner-listing-cover-photo",
    question: "Πώς ορίζω κύρια φωτογραφία;",
    answer:
      "1. Άνοιξε την αγγελία → καρτέλα Φωτογραφίες.\n2. Πάτησε τις τρεις τελείες στη φωτογραφία.\n3. Επίλεξε «Ορισμός ως εξώφυλλο».\n\nΗ εξώφυλλο εμφανίζεται πρώτη στη δημόσια αγγελία και στην αναζήτηση.",
    category: "owner_listing",
    audience: "owner",
    relatedRoutes: [...RW],
    priority: 95,
    quickSuggestion: true,
    suggestionContexts: ["owner_photos", "owner_listing_workspace"],
    aliases: ["Πώς ορίζω εξώφυλλο;"],
    keywords: ["εξωφυλλο", "cover", "κυρια"],
    actionLinks: [{ label: "Φωτογραφίες", href: "/dashboard/listings/{id}/photos" }],
  },
  {
    id: "owner-listing-reorder-photos",
    question: "Πώς αλλάζω τη σειρά των φωτογραφιών;",
    answer:
      "Στην καρτέλα Φωτογραφίες, σύρε τις φωτογραφίες (drag & drop) για νέα σειρά. Η σειρά εμφανίζεται έτσι και στη δημόσια gallery.",
    category: "owner_listing",
    audience: "owner",
    relatedRoutes: [...RW],
    priority: 92,
    quickSuggestion: true,
    suggestionContexts: ["owner_photos"],
    keywords: ["σειρα", "reorder", "drag"],
    actionLinks: [{ label: "Φωτογραφίες", href: "/dashboard/listings/{id}/photos" }],
  },
  {
    id: "owner-listing-rooms",
    question: "Πώς προσθέτω δωμάτια και χώρους;",
    answer:
      "Στην καρτέλα Φωτογραφίες ή Καταχώριση, οργάνωσε φωτογραφίες και περιγραφές ανά χώρο/δωμάτιο. Έτσι οι επισκέπτες βλέπουν δομημένη gallery ανά περιοχή του ακινήτου.",
    category: "owner_listing",
    audience: "owner",
    relatedRoutes: [...RW],
    priority: 75,
    quickSuggestion: true,
    suggestionContexts: ["owner_photos"],
    keywords: ["δωματι", "rooms", "χωροι"],
    actionLinks: [{ label: "Φωτογραφίες", href: "/dashboard/listings/{id}/photos" }],
  },
  {
    id: "owner-listing-amenities",
    question: "Πώς προσθέτω παροχές;",
    answer:
      "1. Άνοιξε την αγγελία → καρτέλα Καταχώριση (edit).\n2. Σκρόλαρε στην ενότητα «Παροχές».\n3. Επίλεξε τις παροχές που ισχύουν.\n4. Πάτησε «Αποθήκευση παροχών».",
    category: "owner_listing",
    audience: "owner",
    relatedRoutes: [...RW],
    priority: 80,
    quickSuggestion: false,
    suggestionContexts: ["owner_listing_workspace"],
    keywords: ["παροχ", "amenities"],
    actionLinks: [{ label: "Καταχώριση", href: "/dashboard/listings/{id}/edit" }],
  },
  {
    id: "owner-listing-set-price",
    question: "Πώς βάζω τιμή;",
    answer:
      "Βραχυχρόνια: καρτέλα Διαθεσιμότητα — βασική τιμή ανά νύχτα, Σαββατοκύριακο, εκπτώσεις.\nΜηνιαία: καρτέλα Καταχώριση — τιμή ανά μήνα.\nΑποθήκευσε τις αλλαγές.",
    category: "owner_listing",
    audience: "owner",
    relatedRoutes: [...RW],
    priority: 93,
    quickSuggestion: true,
    suggestionContexts: ["owner_dashboard", "owner_listing_workspace", "owner_availability"],
    suggestionLabel: "Πώς αλλάζω τιμή;",
    keywords: ["τιμη", "price", "pricing"],
    actionLinks: [{ label: "Διαθεσιμότητα", href: "/dashboard/listings/{id}/availability" }],
  },
  {
    id: "owner-listing-set-availability",
    question: "Πώς βάζω διαθεσιμότητα;",
    answer:
      "1. Άνοιξε την αγγελία → καρτέλα Διαθεσιμότητα.\n2. Κλικ σε ημερομηνία για block/unblock.\n3. Για βραχυχρόνια, όρισε τιμή ανά ημέρα.\n4. Αποθήκευσε.",
    category: "owner_listing",
    audience: "owner",
    relatedRoutes: [...RW],
    priority: 94,
    quickSuggestion: true,
    suggestionContexts: ["owner_dashboard", "owner_availability"],
    suggestionLabel: "Πώς αλλάζω διαθεσιμότητα;",
    keywords: ["διαθεσιμοτητα", "availability", "ημερολογ"],
    actionLinks: [{ label: "Διαθεσιμότητα", href: "/dashboard/listings/{id}/availability" }],
  },
  {
    id: "owner-listing-publish",
    question: "Πώς δημοσιεύω την αγγελία;",
    answer:
      "1. Συμπλήρωσε στοιχεία, φωτογραφίες, τιμές.\n2. Πήγαινε στην καρτέλα Δημοσίευση.\n3. Έλεγξε τις προϋποθέσεις.\n4. Πάτησε Δημοσίευση.\n\nΗ αγγελία εμφανίζεται δημόσια μόνο όταν είναι ενεργή.",
    category: "owner_listing",
    audience: "owner",
    relatedRoutes: [...RW],
    priority: 98,
    quickSuggestion: true,
    suggestionContexts: ["owner_dashboard", "owner_listing_workspace"],
    keywords: ["δημοσιευ", "publish", "live"],
    actionLinks: [{ label: "Δημοσίευση", href: "/dashboard/listings/{id}/publish" }],
  },
  {
    id: "owner-listing-not-public",
    question: "Γιατί η αγγελία μου δεν εμφανίζεται δημόσια;",
    answer:
      "Έλεγξε: (1) καρτέλα Δημοσίευση — είναι ενεργή/δημοσιευμένη; (2) πληρότητα — λείπουν φωτογραφίες/τιμές; (3) status «σε έλεγχο» ή παύση. Διόρθωσε και ξαναδημοσίευσε.",
    category: "owner_listing",
    audience: "owner",
    relatedRoutes: [...RW],
    priority: 87,
    quickSuggestion: false,
    suggestionContexts: ["owner_dashboard", "owner_listing_workspace"],
    keywords: ["δεν εμφανιζ", "not public", "live"],
    actionLinks: [{ label: "Δημοσίευση", href: "/dashboard/listings/{id}/publish" }],
  },
  {
    id: "owner-listing-under-review",
    question: "Τι σημαίνει ότι η αγγελία είναι σε έλεγχο;",
    answer:
      "Η αγγελία μπορεί να είναι προσωρινά μη δημόσια ενώ ελέγχεται ή μέχρι να ολοκληρώσεις απαιτούμενα στοιχεία. Δες την καρτέλα Δημοσίευση για τι λείπει.",
    category: "owner_listing",
    audience: "owner",
    relatedRoutes: [...RW],
    priority: 72,
    quickSuggestion: false,
    suggestionContexts: ["owner_listing_workspace"],
    keywords: ["ελεγχο", "review", "pending"],
  },
  {
    id: "owner-listing-pause",
    question: "Μπορώ να κάνω παύση αγγελίας;",
    answer:
      "Ναι. Από την καρτέλα Δημοσίευση ή τις ρυθμίσεις status, μπορείς να απενεργοποιήσεις/παύσεις την αγγελία. Δεν θα εμφανίζεται στην αναζήτηση μέχρι να την ενεργοποιήσεις ξανά.",
    category: "owner_listing",
    audience: "owner",
    relatedRoutes: [...RW],
    priority: 68,
    quickSuggestion: false,
    suggestionContexts: ["owner_listing_workspace"],
    keywords: ["παυση", "pause", "απενεργοποι"],
    actionLinks: [{ label: "Δημοσίευση", href: "/dashboard/listings/{id}/publish" }],
  },
];
