import type { LucideIcon } from "lucide-react";
import {
  ArrowUpDown,
  Baby,
  Bath,
  BedDouble,
  Briefcase,
  Car,
  ChefHat,
  Coffee,
  Dog,
  Dumbbell,
  Flame,
  Gamepad2,
  Home,
  KeyRound,
  Laptop,
  Leaf,
  MapPin,
  Microwave,
  Monitor,
  Mountain,
  ParkingCircle,
  Refrigerator,
  Shield,
  Shirt,
  Snowflake,
  Sofa,
  Sun,
  Thermometer,
  Tv,
  Umbrella,
  UtensilsCrossed,
  Waves,
  Wifi,
  Wind,
  Zap,
} from "lucide-react";
import type { AmenityCategory } from "@/lib/amenities-catalog-types";
import { AMENITY_BY_KEY } from "@/lib/amenities-catalog";

const CATEGORY_ICONS: Record<AmenityCategory, LucideIcon> = {
  basic: Home,
  bathroom: Bath,
  bedroom_laundry: BedDouble,
  entertainment: Tv,
  family: Baby,
  climate: Thermometer,
  safety: Shield,
  internet_work: Laptop,
  kitchen_dining: ChefHat,
  location_features: MapPin,
  outdoor: Sun,
  parking_facilities: ParkingCircle,
  accessibility: ArrowUpDown,
  services: KeyRound,
  monthly_terms: Sofa,
};

const AMENITY_ICONS: Record<string, LucideIcon> = {
  wifi: Wifi,
  fast_wifi: Wifi,
  ac: Snowflake,
  heating: Flame,
  central_heating: Flame,
  autonomous_heating: Flame,
  radiator: Flame,
  electric_heater: Flame,
  fireplace: Flame,
  washer: Shirt,
  dryer: Wind,
  kitchen: UtensilsCrossed,
  full_kitchen: UtensilsCrossed,
  kitchenette: UtensilsCrossed,
  tv: Tv,
  smart_tv: Tv,
  cable_tv: Tv,
  workspace: Laptop,
  desk: Laptop,
  remote_work_ready: Laptop,
  iron: Shirt,
  hair_dryer: Wind,
  bed_linens: BedDouble,
  balcony: Sun,
  veranda: Sun,
  terrace: Sun,
  view: Waves,
  sea_view: Waves,
  mountain_view: Mountain,
  city_view: MapPin,
  garden_view: Leaf,
  garden: Leaf,
  private_yard: Leaf,
  shared_yard: Leaf,
  yard: Leaf,
  pool: Waves,
  private_pool: Waves,
  shared_pool: Waves,
  hot_tub: Bath,
  bbq: Flame,
  elevator: ArrowUpDown,
  accessible_elevator: ArrowUpDown,
  free_parking: Car,
  street_parking: Car,
  private_parking: Car,
  garage_parking: Car,
  paid_parking_nearby: Car,
  ev_charger: Zap,
  ground_floor: Home,
  self_checkin: KeyRound,
  smart_lock: KeyRound,
  lockbox: KeyRound,
  smoke_detector: Shield,
  co_detector: Shield,
  fire_extinguisher: Shield,
  first_aid: Shield,
  outdoor_lighting: Sun,
  outdoor_security_camera: Shield,
  step_free: ArrowUpDown,
  accessible_bathroom: Bath,
  accessible_entrance: KeyRound,
  pets_allowed: Dog,
  pets_on_request: Dog,
  kid_friendly: Baby,
  infant_friendly: Baby,
  furnished: Sofa,
  partially_furnished: Sofa,
  unfurnished: Home,
  bills_included: Zap,
  electricity_included: Zap,
  water_included: Bath,
  internet_included: Wifi,
  students_suitable: Briefcase,
  professionals_suitable: Briefcase,
  refrigerator: Refrigerator,
  freezer: Refrigerator,
  oven: ChefHat,
  microwave: Microwave,
  coffee_maker: Coffee,
  espresso_machine: Coffee,
  dishwasher: UtensilsCrossed,
  gym: Dumbbell,
  sauna: Bath,
  monitor: Monitor,
  ethernet: Wifi,
  board_games: Gamepad2,
  kids_toys: Baby,
  umbrella: Umbrella,
};

const HIGHLIGHT_ICONS: Record<string, LucideIcon> = {
  key: KeyRound,
  waves: Waves,
  car: Car,
  train: ArrowUpDown,
  users: Sun,
  laptop: Laptop,
  umbrella: Umbrella,
  paw: Dog,
  pool: Waves,
  elevator: ArrowUpDown,
};

export function amenityIconForKey(key: string): LucideIcon {
  if (AMENITY_ICONS[key]) return AMENITY_ICONS[key];
  const category = AMENITY_BY_KEY[key]?.category;
  if (category) return CATEGORY_ICONS[category];
  return Wifi;
}

export function highlightIconForKey(iconKey: string | null | undefined): LucideIcon {
  if (!iconKey) return Sun;
  return HIGHLIGHT_ICONS[iconKey] ?? Sun;
}
