import type { AmenityCategory, AmenityDef, RentalModeScope } from "@/lib/amenities-catalog-types";

type RawAmenity = {
  key: string;
  label: string;
  modes?: RentalModeScope;
  popularShort?: boolean;
  popularMonthly?: boolean;
  safety?: boolean;
  accessibility?: boolean;
};

type CategoryBlock = {
  category: AmenityCategory;
  items: RawAmenity[];
};

function block(category: AmenityCategory, items: RawAmenity[]): CategoryBlock {
  return { category, items };
}

/** Canonical amenity rows grouped by owner/public category. */
export const AMENITY_CATEGORY_BLOCKS: CategoryBlock[] = [
  block("basic", [
    { key: "wifi", label: "Wi-Fi", popularShort: true, popularMonthly: true },
    { key: "towels", label: "Πετσέτες" },
    { key: "sheets", label: "Σεντόνια" },
    { key: "pillows", label: "Μαξιλάρια" },
    { key: "blankets", label: "Κουβέρτες" },
    { key: "toilet_paper", label: "Χαρτί υγείας" },
    { key: "hand_soap", label: "Σαπούνι χεριών" },
    { key: "body_soap", label: "Σαπούνι σώματος" },
    { key: "shampoo", label: "Σαμπουάν" },
    { key: "personal_toiletries", label: "Είδη προσωπικής υγιεινής" },
    { key: "hangers", label: "Κρεμάστρες" },
    { key: "closet", label: "Ντουλάπα / χώρος αποθήκευσης ρούχων" },
    { key: "iron", label: "Σίδερο" },
    { key: "ironing_board", label: "Σιδερώστρα" },
    { key: "hair_dryer", label: "Πιστολάκι μαλλιών" },
    { key: "hot_water", label: "Ζεστό νερό" },
    { key: "cleaning_supplies", label: "Καθαριστικά" },
    { key: "basic_toiletries", label: "Βασικά είδη καθαριότητας" },
    { key: "curtains", label: "Κουρτίνες / σκίαση" },
    { key: "private_entrance", label: "Ιδιωτική είσοδος" },
  ]),
  block("bathroom", [
    { key: "shower", label: "Ντουζ" },
    { key: "bathtub", label: "Μπανιέρα" },
    { key: "conditioner", label: "Conditioner" },
    { key: "bath_towels", label: "Πετσέτες μπάνιου" },
    { key: "face_towels", label: "Πετσέτες προσώπου" },
    { key: "bidet", label: "Μπιντές" },
    { key: "sink", label: "Νιπτήρας" },
    { key: "bathroom_mirror", label: "Καθρέφτης μπάνιου" },
    { key: "bathroom_storage", label: "Αποθηκευτικός χώρος μπάνιου" },
    { key: "washer_in_bathroom", label: "Πλυντήριο ρούχων στο μπάνιο" },
    { key: "toiletries", label: "Προϊόντα περιποίησης" },
    { key: "non_slip_mat", label: "Αντιολισθητικό πατάκι" },
    { key: "flush_toilet", label: "WC με καζανάκι" },
    { key: "private_bathroom", label: "Ιδιωτικό μπάνιο" },
    { key: "shared_bathroom", label: "Κοινόχρηστο μπάνιο" },
  ]),
  block("bedroom_laundry", [
    { key: "washer", label: "Πλυντήριο ρούχων", popularShort: true, popularMonthly: true },
    { key: "dryer", label: "Στεγνωτήριο" },
    { key: "drying_rack", label: "Απλώστρα" },
    { key: "dresser", label: "Συρταριέρα" },
    { key: "extra_sheets", label: "Επιπλέον σεντόνια" },
    { key: "extra_pillows", label: "Επιπλέον μαξιλάρια" },
    { key: "extra_blankets", label: "Επιπλέον κουβέρτες" },
    { key: "blackout_curtains", label: "Σκούρες κουρτίνες / blackout" },
    { key: "mosquito_net", label: "Κουνουπιέρα" },
    { key: "bed_linens", label: "Κλινοσκεπάσματα" },
    { key: "luggage_storage", label: "Χώρος αποσκευών" },
    { key: "safe", label: "Χρηματοκιβώτιο" },
    { key: "queen_bed", label: "Κρεβάτι queen" },
    { key: "king_bed", label: "Κρεβάτι king" },
    { key: "double_bed", label: "Διπλό κρεβάτι" },
    { key: "single_bed", label: "Μονό κρεβάτι" },
    { key: "sofa_bed", label: "Καναπές-κρεβάτι" },
    { key: "bunk_bed", label: "Κουκέτα" },
    { key: "crib", label: "Βρεφική κούνια" },
  ]),
  block("entertainment", [
    { key: "tv", label: "Τηλεόραση", popularShort: true },
    { key: "smart_tv", label: "Smart TV" },
    { key: "cable_tv", label: "Καλωδιακή τηλεόραση" },
    { key: "streaming_apps", label: "Netflix / streaming apps" },
    { key: "sound_system", label: "Ηχοσύστημα" },
    { key: "bluetooth_speaker", label: "Bluetooth speaker" },
    { key: "books", label: "Βιβλία" },
    { key: "board_games", label: "Επιτραπέζια παιχνίδια" },
    { key: "kids_toys", label: "Παιχνίδια για παιδιά" },
    { key: "game_console", label: "Κονσόλα παιχνιδιών" },
    { key: "musical_instruments", label: "Πιάνο / μουσικά όργανα" },
    { key: "projector", label: "Προβολέας" },
    { key: "reading_nook", label: "Χώρος ανάγνωσης" },
  ]),
  block("family", [
    { key: "kid_friendly", label: "Κατάλληλο για παιδιά", popularShort: true },
    { key: "infant_friendly", label: "Κατάλληλο για βρέφη" },
    { key: "pack_n_play", label: "Παρκοκρέβατο" },
    { key: "high_chair", label: "Παιδικό καρεκλάκι" },
    { key: "baby_bath", label: "Μπανιέρα μωρού" },
    { key: "kids_dishes", label: "Παιδικά πιάτα / ποτήρια" },
    { key: "outlet_covers", label: "Προστατευτικά πρίζας" },
    { key: "corner_guards", label: "Προστατευτικά γωνιών" },
    { key: "stair_gates", label: "Κάγκελα ασφαλείας για σκάλες" },
    { key: "furniture_covers", label: "Κάλυμμα επίπλων" },
    { key: "kids_books", label: "Βιβλία για παιδιά" },
    { key: "stroller_available", label: "Καρότσι, αν παρέχεται" },
    { key: "baby_monitor", label: "Βρεφικό monitor, αν παρέχεται" },
  ]),
  block("climate", [
    { key: "ac", label: "Κλιματισμός", popularShort: true, popularMonthly: true },
    { key: "heating", label: "Θέρμανση", popularShort: true, popularMonthly: true },
    { key: "central_heating", label: "Κεντρική θέρμανση" },
    { key: "autonomous_heating", label: "Αυτόνομη θέρμανση" },
    { key: "radiator", label: "Καλοριφέρ" },
    { key: "electric_heater", label: "Ηλεκτρικό καλοριφέρ" },
    { key: "fireplace", label: "Τζάκι" },
    { key: "fan", label: "Ανεμιστήρας" },
    { key: "ceiling_fan", label: "Ανεμιστήρας οροφής" },
    { key: "thermostat", label: "Θερμοστάτης" },
    { key: "dehumidifier", label: "Αφυγραντήρας" },
    { key: "air_purifier", label: "Ιονιστής / καθαριστής αέρα" },
    { key: "double_glazing", label: "Διπλά τζάμια" },
    { key: "sun_shades", label: "Σκίαση / τέντες" },
  ]),
  block("safety", [
    { key: "smoke_detector", label: "Ανιχνευτής καπνού", safety: true },
    { key: "co_detector", label: "Ανιχνευτής μονοξειδίου του άνθρακα", safety: true },
    { key: "fire_extinguisher", label: "Πυροσβεστήρας", safety: true },
    { key: "first_aid", label: "Κουτί πρώτων βοηθειών", safety: true },
    { key: "entry_lock", label: "Κλειδαριά στην κύρια είσοδο", safety: true },
    { key: "bedroom_lock", label: "Κλειδαριά στο υπνοδωμάτιο", safety: true },
    { key: "alarm_system", label: "Συναγερμός", safety: true },
    {
      key: "outdoor_security_camera",
      label: "Κάμερα ασφαλείας εξωτερικού χώρου",
      safety: true,
    },
    { key: "intercom", label: "Θυροτηλέφωνο", safety: true },
    { key: "video_intercom", label: "Βιντεοθυροτηλέφωνο", safety: true },
    { key: "outdoor_lighting", label: "Φωτισμός ασφαλείας", safety: true },
    { key: "emergency_exit", label: "Έξοδος κινδύνου", safety: true },
    { key: "safety_rails", label: "Κάγκελα / προστατευτικά", safety: true },
    { key: "anti_slip_mats", label: "Αντιολισθητικά πατάκια", safety: true },
  ]),
  block("internet_work", [
    { key: "fast_wifi", label: "Γρήγορο Wi-Fi" },
    { key: "ethernet", label: "Ενσύρματη σύνδεση Internet" },
    { key: "workspace", label: "Χώρος εργασίας", popularShort: true, popularMonthly: true },
    { key: "desk", label: "Γραφείο" },
    { key: "office_chair", label: "Καρέκλα γραφείου" },
    { key: "desk_lamp", label: "Φωτισμός γραφείου" },
    { key: "laptop_stand", label: "Laptop stand" },
    { key: "monitor", label: "Οθόνη" },
    { key: "printer", label: "Εκτυπωτής" },
    { key: "power_strip", label: "Πολύμπριζο" },
    { key: "universal_charger", label: "Universal charger" },
    { key: "quiet_workspace", label: "Ήσυχος χώρος εργασίας" },
    { key: "remote_work_ready", label: "Κατάλληλο για remote work" },
  ]),
  block("kitchen_dining", [
    { key: "kitchen", label: "Κουζίνα", popularShort: true, popularMonthly: true },
    { key: "full_kitchen", label: "Πλήρως εξοπλισμένη κουζίνα" },
    { key: "kitchenette", label: "Μικρή κουζίνα / kitchenette" },
    { key: "refrigerator", label: "Ψυγείο" },
    { key: "freezer", label: "Καταψύκτης" },
    { key: "oven", label: "Φούρνος" },
    { key: "stove", label: "Εστίες" },
    { key: "ceramic_stove", label: "Κεραμικές εστίες" },
    { key: "induction_stove", label: "Επαγωγικές εστίες" },
    { key: "microwave", label: "Φούρνος μικροκυμάτων" },
    { key: "dishwasher", label: "Πλυντήριο πιάτων" },
    { key: "coffee_maker", label: "Καφετιέρα" },
    { key: "espresso_machine", label: "Καφετιέρα espresso" },
    { key: "kettle", label: "Βραστήρας" },
    { key: "toaster", label: "Τοστιέρα" },
    { key: "blender", label: "Μπλέντερ" },
    { key: "cookware_and_dishes", label: "Μαγειρικά σκεύη και πιάτα" },
    { key: "cookware", label: "Μαγειρικά σκεύη" },
    { key: "pots_pans", label: "Κατσαρόλες / τηγάνια" },
    { key: "dishes_cutlery", label: "Πιάτα και μαχαιροπίρουνα" },
    { key: "glasses", label: "Ποτήρια" },
    { key: "mugs", label: "Κούπες" },
    { key: "knives", label: "Μαχαίρια" },
    { key: "cutting_board", label: "Επιφάνεια κοπής" },
    { key: "basic_spices", label: "Αλάτι / πιπέρι / βασικά μπαχαρικά" },
    { key: "oil_vinegar", label: "Λάδι / ξύδι, αν παρέχεται" },
    { key: "dining_table", label: "Τραπέζι φαγητού" },
    { key: "dining_chairs", label: "Καρέκλες τραπεζαρίας" },
    { key: "kids_high_chair", label: "Παιδικό καρεκλάκι" },
    { key: "trash_bin", label: "Κάδος απορριμμάτων" },
    { key: "recycling_bin", label: "Κάδος ανακύκλωσης" },
    { key: "kitchen_cleaning", label: "Καθαριστικά κουζίνας" },
    { key: "dish_sponge", label: "Σφουγγάρι / υγρό πιάτων" },
  ]),
  block("location_features", [
    { key: "sea_view", label: "Θέα στη θάλασσα" },
    { key: "mountain_view", label: "Θέα στο βουνό" },
    { key: "city_view", label: "Θέα στην πόλη" },
    { key: "garden_view", label: "Θέα σε κήπο" },
    { key: "yard_view", label: "Θέα σε αυλή" },
    { key: "near_sea", label: "Κοντά στη θάλασσα" },
    { key: "beachfront", label: "Μπροστά στη θάλασσα" },
    { key: "near_metro", label: "Κοντά σε μετρό" },
    { key: "near_bus", label: "Κοντά σε στάση λεωφορείου" },
    { key: "near_city_center", label: "Κοντά σε κέντρο πόλης" },
    { key: "quiet_neighborhood", label: "Ήσυχη γειτονιά" },
    { key: "near_supermarket", label: "Κοντά σε αγορά / supermarket" },
    { key: "near_hospital", label: "Κοντά σε νοσοκομείο" },
    { key: "near_university", label: "Κοντά σε πανεπιστήμιο" },
    { key: "near_beach", label: "Κοντά σε παραλία" },
    { key: "near_ski", label: "Κοντά σε χιονοδρομικό" },
    { key: "ground_floor", label: "Ισόγειο" },
    { key: "penthouse", label: "Ρετιρέ" },
    { key: "in_apartment_building", label: "Σε πολυκατοικία" },
    { key: "detached_house", label: "Μονοκατοικία" },
  ]),
  block("outdoor", [
    { key: "balcony", label: "Μπαλκόνι ή βεράντα", popularShort: true },
    { key: "veranda", label: "Βεράντα" },
    { key: "private_yard", label: "Ιδιωτική αυλή" },
    { key: "shared_yard", label: "Κοινόχρηστη αυλή" },
    { key: "garden", label: "Κήπος" },
    { key: "terrace", label: "Ταράτσα" },
    { key: "yard", label: "Αυλή ή κήπος" },
    { key: "bbq", label: "BBQ", popularShort: true },
    { key: "outdoor_furniture", label: "Εξωτερικά έπιπλα" },
    { key: "outdoor_dining", label: "Τραπεζαρία εξωτερικού χώρου" },
    { key: "sun_loungers", label: "Ξαπλώστρες" },
    { key: "umbrella", label: "Ομπρέλα" },
    { key: "outdoor_shower", label: "Εξωτερικό ντουζ" },
    { key: "private_pool", label: "Ιδιωτική πισίνα", popularShort: true },
    { key: "shared_pool", label: "Κοινόχρηστη πισίνα" },
    { key: "hot_tub", label: "Υδρομασάζ / Jacuzzi", popularShort: true },
    { key: "playground", label: "Παιδική χαρά" },
    { key: "outdoor_view", label: "Θέα από εξωτερικό χώρο" },
    { key: "view", label: "Θέα" },
    { key: "pool", label: "Πισίνα" },
  ]),
  block("parking_facilities", [
    { key: "free_parking", label: "Δωρεάν parking στον χώρο", popularShort: true, popularMonthly: true },
    { key: "street_parking", label: "Parking στον δρόμο" },
    { key: "paid_parking_nearby", label: "Πληρωμένο parking κοντά" },
    { key: "private_parking", label: "Ιδιωτικό parking" },
    { key: "garage_parking", label: "Parking σε γκαράζ" },
    { key: "ev_charger", label: "Φορτιστής ηλεκτρικού αυτοκινήτου" },
    { key: "elevator", label: "Ανελκυστήρας" },
    { key: "gym", label: "Γυμναστήριο" },
    { key: "sauna", label: "Σάουνα" },
    { key: "shared_spaces", label: "Κοινόχρηστοι χώροι" },
    { key: "storage_room", label: "Αποθήκη" },
    { key: "luggage_storage", label: "Φύλαξη αποσκευών" },
    { key: "luggage_room", label: "Χώρος φύλαξης αποσκευών" },
    { key: "bike_storage", label: "Θέση για ποδήλατο" },
    { key: "key_access", label: "Πρόσβαση με κλειδί" },
    { key: "self_checkin", label: "Self check-in", popularShort: true },
    { key: "smart_lock", label: "Smart lock" },
    { key: "lockbox", label: "Lockbox" },
    { key: "reception", label: "Υποδοχή / reception" },
  ]),
  block("accessibility", [
    { key: "wheelchair_access", label: "Πρόσβαση για ΑμεΑ", accessibility: true },
    { key: "step_free", label: "Είσοδος χωρίς σκαλοπάτια", accessibility: true },
    { key: "accessible_elevator", label: "Ασανσέρ", accessibility: true },
    { key: "wide_entrance", label: "Φαρδιά είσοδος", accessibility: true },
    { key: "wide_doors", label: "Φαρδιές πόρτες", accessibility: true },
    { key: "step_free_hallways", label: "Διάδρομοι χωρίς σκαλοπάτια", accessibility: true },
    { key: "accessible_bathroom", label: "Προσβάσιμο μπάνιο", accessibility: true },
    { key: "shower_grab_bars", label: "Χειρολαβές στο ντουζ", accessibility: true },
    { key: "toilet_grab_bars", label: "Χειρολαβές στην τουαλέτα", accessibility: true },
    { key: "shower_chair", label: "Καρέκλα ντουζ", accessibility: true },
    { key: "roll_in_shower", label: "Ντουζ χωρίς σκαλοπάτι", accessibility: true },
    { key: "accessible_parking", label: "Προσβάσιμο parking", accessibility: true },
    { key: "lit_entry_path", label: "Καλή φωταγώγηση διαδρομής εισόδου", accessibility: true },
    { key: "ground_floor_bedroom", label: "Υπνοδωμάτιο στο ισόγειο", accessibility: true },
    { key: "ground_floor_bathroom", label: "Μπάνιο στο ισόγειο", accessibility: true },
    { key: "accessible_entrance", label: "Προσβάσιμη είσοδος", accessibility: true },
  ]),
  block("services", [
    { key: "pets_allowed", label: "Επιτρέπονται κατοικίδια", popularShort: true, popularMonthly: true },
    { key: "flexible_checkin", label: "Ευέλικτο check-in" },
    { key: "host_checkin", label: "Check-in με ιδιοκτήτη" },
    { key: "mid_stay_cleaning", label: "Καθαρισμός κατά τη διαμονή, αν παρέχεται" },
    { key: "linen_service", label: "Αλλαγή σεντονιών, αν παρέχεται" },
    { key: "luggage_help", label: "Φύλαξη αποσκευών" },
    { key: "airport_transfer", label: "Μεταφορά από/προς αεροδρόμιο, αν παρέχεται" },
    { key: "breakfast", label: "Πρωινό, αν παρέχεται" },
    { key: "smoking_allowed", label: "Επιτρέπεται το κάπνισμα" },
    { key: "no_smoking", label: "Δεν επιτρέπεται το κάπνισμα" },
    { key: "events_allowed", label: "Επιτρέπονται εκδηλώσεις" },
    { key: "no_parties", label: "Δεν επιτρέπονται πάρτι" },
    { key: "long_stay_allowed", label: "Μακροχρόνια διαμονή επιτρέπεται" },
    { key: "autonomous_access", label: "Αυτόνομη πρόσβαση" },
  ]),
  block("monthly_terms", [
    { key: "furnished", label: "Επιπλωμένο", modes: "monthly", popularMonthly: true },
    { key: "partially_furnished", label: "Μερικώς επιπλωμένο", modes: "monthly" },
    { key: "unfurnished", label: "Μη επιπλωμένο", modes: "monthly" },
    { key: "bills_included", label: "Λογαριασμοί περιλαμβάνονται", modes: "monthly", popularMonthly: true },
    { key: "electricity_included", label: "Ρεύμα περιλαμβάνεται", modes: "monthly" },
    { key: "water_included", label: "Νερό περιλαμβάνεται", modes: "monthly" },
    { key: "internet_included", label: "Internet περιλαμβάνεται", modes: "monthly" },
    { key: "common_charges_included", label: "Κοινόχρηστα περιλαμβάνονται", modes: "monthly" },
    { key: "heating_included", label: "Θέρμανση περιλαμβάνεται", modes: "monthly" },
    { key: "students_suitable", label: "Κατάλληλο για φοιτητές", modes: "monthly", popularMonthly: true },
    { key: "professionals_suitable", label: "Κατάλληλο για επαγγελματίες", modes: "monthly", popularMonthly: true },
    { key: "pets_on_request", label: "Κατοικίδια κατόπιν συνεννόησης", modes: "monthly" },
    { key: "lease_available", label: "Συμβόλαιο διαθέσιμο", modes: "monthly" },
    { key: "deposit_required", label: "Εγγύηση", modes: "monthly" },
  ]),
];

let sortCounter = 0;

export function buildAmenitiesCatalog(): AmenityDef[] {
  const seen = new Set<string>();
  const catalog: AmenityDef[] = [];

  for (const { category, items } of AMENITY_CATEGORY_BLOCKS) {
    for (const item of items) {
      if (seen.has(item.key)) continue;
      seen.add(item.key);
      sortCounter += 10;
      catalog.push({
        key: item.key,
        label: item.label,
        category,
        modes: item.modes ?? "both",
        isPopularFilterShort: Boolean(item.popularShort),
        isPopularFilterMonthly: Boolean(item.popularMonthly),
        isSafetyFeature: Boolean(item.safety),
        isAccessibilityFeature: Boolean(item.accessibility),
        sortOrder: sortCounter,
      });
    }
  }

  return catalog;
}

/** Legacy key aliases kept for seeded/demo rows and older wizard selections. */
export const LEGACY_AMENITY_KEY_ALIASES: Record<string, string> = {
  linens: "bed_linens",
  toiletries: "personal_toiletries",
  basic_toiletries: "personal_toiletries",
  cookware: "cookware_and_dishes",
  dishes_cutlery: "cookware_and_dishes",
  pots_pans: "cookware_and_dishes",
  veranda: "balcony",
  terrace: "balcony",
  garden: "yard",
  private_yard: "yard",
  kids_high_chair: "high_chair",
  luggage_help: "luggage_storage",
  luggage_room: "luggage_storage",
  accessible_entrance: "wheelchair_access",
  accessible_elevator: "elevator",
};

export const SHORT_TERM_RECOMMENDED_KEYS = [
  "wifi",
  "towels",
  "sheets",
  "toilet_paper",
  "hand_soap",
  "hot_water",
] as const;

export const MONTHLY_RECOMMENDED_KEYS = [
  "kitchen",
  "washer",
  "heating",
  "wifi",
  "closet",
  "bills_included",
] as const;
