// Auto-generated by scripts/generate-build-info.ts — do not edit.
export const BUILD_INFO = {
  gitHash: "778fdbc",
  gitSubject: "Stabilize owner listing workspace: continue completion, pricing tabs, and map house marker.",
  builtAt: "2026-07-29T12:49:21.195Z",
  environment: "development",
} as const;
