// Auto-generated by scripts/generate-build-info.ts — do not edit.
export const BUILD_INFO = {
  gitHash: "c6ee725",
  gitSubject: "Improve trust-links UX and fix clipped external link modal.",
  builtAt: "2026-07-28T15:54:24.186Z",
  environment: "development",
} as const;
