// Auto-generated by scripts/generate-build-info.ts — do not edit.
export const BUILD_INFO = {
  gitHash: "d146a3f",
  gitSubject: "Save complete Midora state: listing sticky layout, search polish, i18n.",
  builtAt: "2026-07-28T22:36:28.560Z",
  environment: "development",
} as const;
