/**
 * Spitogatos area IDs — ηπειρωτική Ελλάδα & μεγάλα αστικά κέντρα.
 * Νησιά εξαιρούνται (θα προστεθούν αργότερα με θέα θάλασσα).
 *
 * IDs από search-results-map XHR στο spitogatos.gr (βλ. Apify actor README).
 */
export type MainlandArea = {
  areaId: string;
  city: string;
  region: string;
};

export const MAINLAND_SPIOGATOS_AREAS: MainlandArea[] = [
  { areaId: "100", city: "Αθήνα", region: "Αττική" },
  { areaId: "5", city: "Αθήνα", region: "Αττική" },
  { areaId: "6", city: "Αθήνα", region: "Αττική" },
  { areaId: "4", city: "Αθήνα", region: "Αττική" },
  { areaId: "8", city: "Πειραιάς", region: "Αττική" },
  { areaId: "21", city: "Γλυφάδα", region: "Αττική" },
  { areaId: "73", city: "Κηφισιά", region: "Αττική" },
  { areaId: "84", city: "Μαρούσι", region: "Αττική" },
  { areaId: "14", city: "Θεσσαλονίκη", region: "Κεντρική Μακεδονία" },
  { areaId: "90", city: "Πάτρα", region: "Δυτική Ελλάδα" },
  { areaId: "120", city: "Λάρισα", region: "Θεσσαλία" },
  { areaId: "130", city: "Βόλος", region: "Θεσσαλία" },
  { areaId: "140", city: "Ιωάννινα", region: "Ήπειρος" },
  { areaId: "150", city: "Καβάλα", region: "Ανατολική Μακεδονία" },
  { areaId: "160", city: "Αλεξανδρούπολη", region: "Ανατολική Μακεδονία" },
  { areaId: "170", city: "Κομοτηνή", region: "Ανατολική Μακεδονία" },
  { areaId: "180", city: "Σέρρες", region: "Κεντρική Μακεδονία" },
  { areaId: "190", city: "Κατερίνη", region: "Κεντρική Μακεδονία" },
  { areaId: "200", city: "Βέροια", region: "Κεντρική Μακεδονία" },
  { areaId: "210", city: "Κοζάνη", region: "Δυτική Μακεδονία" },
  { areaId: "220", city: "Φλώρινα", region: "Δυτική Μακεδονία" },
  { areaId: "230", city: "Καστοριά", region: "Δυτική Μακεδονία" },
  { areaId: "240", city: "Τρίκαλα", region: "Θεσσαλία" },
  { areaId: "250", city: "Καρδίτσα", region: "Θεσσαλία" },
  { areaId: "260", city: "Λαμία", region: "Στερεά Ελλάδα" },
  { areaId: "270", city: "Χαλκίδα", region: "Στερεά Ελλάδα" },
  { areaId: "280", city: "Θήβα", region: "Στερεά Ελλάδα" },
  { areaId: "290", city: "Κόρινθος", region: "Πελοπόννησος" },
  { areaId: "300", city: "Τρίπολη", region: "Πελοπόννησος" },
  { areaId: "310", city: "Καλαμάτα", region: "Πελοπόννησος" },
  { areaId: "320", city: "Ναύπλιο", region: "Πελοπόννησος" },
  { areaId: "330", city: "Σπάρτη", region: "Πελοπόννησος" },
  { areaId: "340", city: "Πύργος", region: "Πελοπόννησος" },
  { areaId: "350", city: "Αγρίνιο", region: "Δυτική Ελλάδα" },
  { areaId: "360", city: "Άρτα", region: "Ήπειρος" },
  { areaId: "370", city: "Πρέβεζα", region: "Ήπειρος" },
  { areaId: "380", city: "Μεσολόγγι", region: "Δυτική Ελλάδα" },
  { areaId: "390", city: "Ξάνθη", region: "Ανατολική Μακεδονία" },
  { areaId: "400", city: "Δράμα", region: "Ανατολική Μακεδονία" },
  { areaId: "410", city: "Πτολεμαΐδα", region: "Δυτική Μακεδονία" },
  { areaId: "420", city: "Γρεβενά", region: "Δυτική Μακεδονία" },
  { areaId: "430", city: "Λιβαδειά", region: "Στερεά Ελλάδα" },
  { areaId: "440", city: "Αμφισσα", region: "Στερεά Ελλάδα" },
  { areaId: "450", city: "Κιλκίς", region: "Κεντρική Μακεδονία" },
  { areaId: "460", city: "Έδεσσα", region: "Κεντρική Μακεδονία" },
  { areaId: "470", city: "Γιαννιτσά", region: "Κεντρική Μακεδονία" },
  { areaId: "480", city: "Κατερίνη", region: "Κεντρική Μακεδονία" },
  { areaId: "490", city: "Χαλκιδική", region: "Κεντρική Μακεδονία" },
];

/** Νησιωτικές περιοχές — αποκλείονται από το import (προς το παρόν). */
export const ISLAND_GEO_KEYWORDS = [
  "σαντορίνη",
  "santorini",
  "μύκονος",
  "mykonos",
  "κρήτη",
  "crete",
  "ηράκλειο",
  "heraklion",
  "χανιά",
  "chania",
  "ρέθυμνο",
  "rethymno",
  "ρόδος",
  "rhodes",
  "κέρκυρα",
  "corfu",
  "ζάκυνθος",
  "zante",
  "κεφαλονιά",
  "kefalonia",
  "λέσβος",
  "lesvos",
  "mytilene",
  "χίος",
  "chios",
  "σάμος",
  "samos",
  "πάρος",
  "paros",
  "νάξος",
  "naxos",
  "ανδρός",
  "andros",
  "τήνος",
  "tinos",
  "σύρος",
  "syros",
  "κως",
  "kos",
  "καλύμνος",
  "kalymnos",
  "λευκάδα",
  "lefkada",
  "σκιάθος",
  "skiathos",
  "σκόπελος",
  "skopelos",
  "αλόννησος",
  "alonissos",
  "θάσος",
  "thasos",
  "ικαρία",
  "ikaria",
  "λήμνος",
  "limnos",
  "κάρπαθος",
  "karpathos",
];

export function isIslandGeography(text: string): boolean {
  const lower = text.toLowerCase();
  return ISLAND_GEO_KEYWORDS.some((kw) => lower.includes(kw));
}
