import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const outPath = join(root, "src", "lib", "build-info.generated.ts");

function readGit(field: string): string {
  try {
    return execSync(`git log -1 --format=${field}`, {
      cwd: root,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    return "unknown";
  }
}

const hash = readGit("%h");
const subject = readGit("%s");
const builtAt = new Date().toISOString();
const env = process.env.NODE_ENV ?? "development";

const content = `// Auto-generated by scripts/generate-build-info.ts — do not edit.
export const BUILD_INFO = {
  gitHash: ${JSON.stringify(hash)},
  gitSubject: ${JSON.stringify(subject)},
  builtAt: ${JSON.stringify(builtAt)},
  environment: ${JSON.stringify(env)},
} as const;
`;

writeFileSync(outPath, content, "utf8");
console.log(`Build info: ${hash} (${env})`);
